# Model Creation & Analysis

Two models will be created with Meta's Prophet. The first one will be a baseline with just the rental data while the other will use the unemployment of VA as an additional regressor. Afterwards, the models will be finetuned and analysis will be performed to examine the performances.

## Outline 
* Base model creation
* Model with additional unemployment regressor
* Midway comparison
* Fine tuning
* Statistical Analysis

In [1]:
from pyprojroot.here import here
import pandas as pd
import os

# Set the cwd to the project's root
os.chdir(here())
print(f"Current working directory: {os.getcwd()}")

Current working directory: /Users/jam/Documents/ds/MI1-2

In [2]:
import pandas as pd
# Create dataframe for combined data
combined_data = pd.read_csv('DATA/Charlottesville_Rent_Employment_Master.csv')

# Preview data
print( "COMBINED DATA")
combined_data.head(10)

COMBINED DATA

           ds            y  employment_count
0  2015-01-31  1030.293753          103503.0
1  2015-02-28  1033.140296          105522.0
2  2015-03-31  1036.707494          105700.0
3  2015-04-30  1057.235869          107064.0
4  2015-05-31  1060.458311          105949.0
5  2015-06-30  1066.297180          104874.0
6  2015-07-31  1063.034752          104150.0
7  2015-08-31  1071.748772          102822.0
8  2015-09-30  1080.462792          105301.0
9  2015-10-31  1102.797649          105007.0

First we have to account for COVID. Prophet has a "holiday" feature which we will use to account for the dip in our data. Through looking at our graphs and reflecting on our experience we decided on Jan - March 2020 with a lower window of 1 month and upper window of 3 months.

* `lower_window` : effect of the holiday that extends *before* the holiday begins
* `upper_window` : effect of the holiday that extends *after* the holiday ends

In [3]:
covid_dates = pd.date_range(start='2020-01-01', end='2020-03-31')
covid = pd.DataFrame({
  'holiday': 'covid',
  'ds': covid_dates,
  'lower_window': -30, # Lower window = effects that may have occured prior to covid ~ 1 month
  'upper_window': 90, # Upper window = effects that may have lasted past covid ~ 3 months
})

## Model 1: Base Model Creation

No NAN values should exist as the data was interpolated previously. Fitting the model will be limited to dates in 2024 so we can compare with the actual values in 2025.

In [4]:
from prophet import Prophet

# Take only the date and rental data from the combined data
rental_data = combined_data[['ds', 'y']].copy()
# Limit to 2024
rental_data = rental_data[rental_data['ds'] <= '2024-12-31']

m1 = Prophet(holidays=covid)
m1.fit(rental_data)

# Build the model excluding the year of 2025 
future = m1.make_future_dataframe(periods=12, freq='ME')
# Predict 2025 data
forecast1 = m1.predict(future)

# Create a data frame with yhat as the predicted value per row and columns for uncertainty levels
forecast1[['ds', 'yhat', 'yhat_lower', 'yhat_upper']].tail(12)

Importing plotly failed. Interactive plots will not work.
16:15:23 - cmdstanpy - INFO - Chain [1] start processing
16:15:23 - cmdstanpy - INFO - Chain [1] done processing
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: divide by zero encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: overflow encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: invalid value encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: divide by zero encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: overflow encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: invalid value encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: divide by zero encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: overflow encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: invalid value encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)

            ds         yhat   yhat_lower   yhat_upper
120 2025-01-31  1831.227179  1812.205556  1851.392922
121 2025-02-28  1832.696562  1815.079412  1851.177319
122 2025-03-31  1847.027733  1829.511656  1866.974236
123 2025-04-30  1866.787131  1846.731241  1885.166009
124 2025-05-31  1874.536675  1856.988928  1893.085120
125 2025-06-30  1883.439654  1865.153371  1901.967574
126 2025-07-31  1892.294027  1873.660187  1911.230276
127 2025-08-31  1896.911332  1877.847144  1916.442693
128 2025-09-30  1905.019240  1885.328326  1923.972061
129 2025-10-31  1912.996144  1894.407384  1933.029321
130 2025-11-30  1915.580941  1895.465427  1934.471760
131 2025-12-31  1921.073403  1902.061105  1940.835493

## Model 2: Model with Unemployment Regressor

In [5]:
# Technically the same as the combined data set, but creating a copy for cleaner handling
rental_and_employment = combined_data[['ds', 'y', 'employment_count']].copy()
# Limit to end of 2024
rental_and_employment = rental_and_employment[rental_and_employment['ds'] <= '2024-12-31']

m2 = Prophet(holidays=covid)
# Registering the employment data as an additional regressor
m2.add_regressor('employment_count')
m2.fit(rental_and_employment)

# Build the model excluding the year of 2025 
future2 = m2.make_future_dataframe(periods=12, freq='ME')

# Prophet requires that regressor values be present in both fitting and prediction df
# Therefore the employment count will track to 2025 following real data
# First ensure dataframes are of the same type
combined_data['ds'] = pd.to_datetime(combined_data['ds'])
future2['ds'] = pd.to_datetime(future2['ds'])

# Merge data together to add 2025 employment count
future2 = future2.merge(
    combined_data[['ds', 'employment_count']],
    on='ds',
    how='left'
)
# Actual prediction
forecast2 = m2.predict(future2)

# Create a data frame with yhat as the predicted value per row and columns for uncertainty levels
forecast2[['ds', 'yhat', 'yhat_lower', 'yhat_upper']].tail(12)

16:15:24 - cmdstanpy - INFO - Chain [1] start processing
16:15:24 - cmdstanpy - INFO - Chain [1] done processing
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: divide by zero encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: overflow encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: invalid value encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: divide by zero encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: overflow encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: invalid value encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: divide by zero encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: overflow encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: invalid value encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)

            ds         yhat   yhat_lower   yhat_upper
120 2025-01-31  1832.144667  1814.390510  1850.593300
121 2025-02-28  1832.468818  1813.366834  1851.085686
122 2025-03-31  1846.462016  1826.799140  1866.491789
123 2025-04-30  1865.385866  1847.277789  1883.201891
124 2025-05-31  1872.314633  1853.153787  1892.423304
125 2025-06-30  1881.708063  1862.484731  1899.531220
126 2025-07-31  1890.923337  1872.457987  1909.473297
127 2025-08-31  1895.872872  1877.113864  1914.667010
128 2025-09-30  1902.161829  1883.562170  1921.053997
129 2025-10-31  1909.878830  1890.898578  1929.131754
130 2025-11-30  1912.812333  1893.319146  1932.180239
131 2025-12-31  1919.339272  1899.389581  1939.467158

## Midway Comparison
Now that the rental data has been forecasted by the two models, we can do a preliminary comparison before any statistical tests.

In [6]:
# Pull actual values from the year of 2025
actual_values = combined_data[combined_data['ds'] >= '2025-01-01'][['ds', 'y']].copy()

# Pull the model performances 
f1 = forecast1[forecast1['ds'] >= '2025-01-01'][['ds', 'yhat', 'yhat_lower', 'yhat_upper']].rename(
    columns={'yhat': 'yhat_m1', 'yhat_lower': 'lower_m1', 'yhat_upper': 'upper_m1'})
f2 = forecast2[forecast2['ds'] >= '2025-01-01'][['ds', 'yhat', 'yhat_lower', 'yhat_upper']].rename(
    columns={'yhat': 'yhat_m2', 'yhat_lower': 'lower_m2', 'yhat_upper': 'upper_m2'})

# Merge all the data together for easy comparison
midway_comparison = actual_values.merge(f1, on='ds').merge(f2, on='ds')
# Check whether the actual value falls between the upper and lower ends of the model's prediction
midway_comparison['within_m1'] = midway_comparison['y'].between(midway_comparison['lower_m1'], midway_comparison['upper_m1'])
midway_comparison['within_m2'] = midway_comparison['y'].between(midway_comparison['lower_m2'], midway_comparison['upper_m2'])
# Confidence levels
midway_comparison['width_m1'] = midway_comparison['upper_m1'] - midway_comparison['lower_m1']
midway_comparison['width_m2'] = midway_comparison['upper_m2'] - midway_comparison['lower_m2']

print(midway_comparison[['ds', 'y', 'yhat_m1', 'within_m1', 'yhat_m2', 'within_m2']])
print(f"\nM1 coverage: {midway_comparison['within_m1'].mean():.0%}")
print(f"M2 coverage: {midway_comparison['within_m2'].mean():.0%}")
print(f"M1 avg interval width: {midway_comparison['width_m1'].mean():.2f}")
print(f"M2 avg interval width: {midway_comparison['width_m2'].mean():.2f}")

           ds            y      yhat_m1  within_m1      yhat_m2  within_m2
0  2025-01-31  1810.942452  1831.227179      False  1832.144667      False
1  2025-02-28  1853.575750  1832.696562      False  1832.468818      False
2  2025-03-31  1873.731004  1847.027733      False  1846.462016      False
3  2025-04-30  1873.613465  1866.787131       True  1865.385866       True
4  2025-05-31  1885.487821  1874.536675       True  1872.314633       True
5  2025-06-30  1895.184392  1883.439654       True  1881.708063       True
6  2025-07-31  1907.515917  1892.294027       True  1890.923337       True
7  2025-08-31  1898.018927  1896.911332       True  1895.872872       True
8  2025-09-30  1943.949582  1905.019240      False  1902.161829      False
9  2025-10-31  1952.670747  1912.996144      False  1909.878830      False
10 2025-11-30  1947.121214  1915.580941      False  1912.812333      False
11 2025-12-31  1908.264675  1921.073403       True  1919.339272       True

M1 coverage: 50%
M2 coverage: 50%
M1 avg interval width: 37.94
M2 avg interval width: 37.92

## Finetuning 
The models did not perform as well as initially believed, but we will continue with finetuning to see if we can improve the performance.

In [ ]:
from prophet.diagnostics import cross_validation, performance_metrics
import itertools
import numpy as np

# Paraneter grid 
param_grid = {
    'changepoint_prior_scale': [0.01, 0.05, 0.1], 
    'seasonality_prior_scale': [0.1, 1.0, 10.0],
    'changepoint_range': [0.8, 0.9, 0.95]
}

# Generate all combinations of params
all_params = [dict(zip(param_grid.keys(), v)) for v in itertools.product(*param_grid.values())]

# First finetune the base model
rmses_m1 = []  # RMSEs values for the parameters for model 1 

for params in all_params:
    m = Prophet(holidays=covid, **params)
    m.fit(rental_data)
    
    df_cv = cross_validation(m, initial='1825 days', period='180 days', horizon='365 days')
    df_p = performance_metrics(df_cv, rolling_window=1)
    rmses_m1.append(df_p['mae'].values[0])

# Find the best params
best_params_m1 = all_params[np.argmin(rmses_m1)]
print(f" Best parameters for base model: {best_params_m1}")

16:15:25 - cmdstanpy - INFO - Chain [1] start processing
16:15:25 - cmdstanpy - INFO - Chain [1] done processing

  0%|          | 0/8 [00:00<?, ?it/s]

16:15:25 - cmdstanpy - INFO - Chain [1] start processing
16:15:26 - cmdstanpy - INFO - Chain [1] done processing
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: divide by zero encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: overflow encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: invalid value encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: divide by zero encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: overflow encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: invalid value encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: divide by zero encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: overflow encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: invalid value encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
16:15:27 - cmdstanpy - INFO - Chain [1] start processing
16:15:28 - cmdstanpy - INFO - Chain [1] done processing
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: divide by zero encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: overflow encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: invalid value encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: divide by zero encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: overflow encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: invalid value encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: divide by zero encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: overflow encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: invalid value encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
16:15:29 - cmdstanpy - INFO - Chain [1] start processing
16:15:30 - cmdstanpy - INFO - Chain [1] done processing
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: divide by zero encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: overflow encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: invalid value encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: divide by zero encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: overflow encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: invalid value encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: divide by zero encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: overflow encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: invalid value encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
16:15:30 - cmdstanpy - INFO - Chain [1] start processing
16:15:31 - cmdstanpy - INFO - Chain [1] done processing
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: divide by zero encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: overflow encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: invalid value encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: divide by zero encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: overflow encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: invalid value encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: divide by zero encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: overflow encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: invalid value encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
16:15:32 - cmdstanpy - INFO - Chain [1] start processing
16:15:34 - cmdstanpy - INFO - Chain [1] done processing
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: divide by zero encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: overflow encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: invalid value encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: divide by zero encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: overflow encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: invalid value encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: divide by zero encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: overflow encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: invalid value encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
16:15:35 - cmdstanpy - INFO - Chain [1] start processing
16:15:36 - cmdstanpy - INFO - Chain [1] done processing
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: divide by zero encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: overflow encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: invalid value encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: divide by zero encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: overflow encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: invalid value encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: divide by zero encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: overflow encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: invalid value encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
16:15:37 - cmdstanpy - INFO - Chain [1] start processing
16:15:37 - cmdstanpy - INFO - Chain [1] done processing
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: divide by zero encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: overflow encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: invalid value encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: divide by zero encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: overflow encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: invalid value encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: divide by zero encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: overflow encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: invalid value encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
16:15:38 - cmdstanpy - INFO - Chain [1] start processing
16:15:38 - cmdstanpy - INFO - Chain [1] done processing
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: divide by zero encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: overflow encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: invalid value encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: divide by zero encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: overflow encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: invalid value encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: divide by zero encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: overflow encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: invalid value encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
16:15:39 - cmdstanpy - INFO - Chain [1] start processing
16:15:39 - cmdstanpy - INFO - Chain [1] done processing

  0%|          | 0/8 [00:00<?, ?it/s]

16:15:39 - cmdstanpy - INFO - Chain [1] start processing
16:15:40 - cmdstanpy - INFO - Chain [1] done processing
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: divide by zero encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: overflow encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: invalid value encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: divide by zero encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: overflow encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: invalid value encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: divide by zero encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: overflow encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: invalid value encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
16:15:41 - cmdstanpy - INFO - Chain [1] start processing
16:15:42 - cmdstanpy - INFO - Chain [1] done processing
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: divide by zero encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: overflow encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: invalid value encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: divide by zero encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: overflow encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: invalid value encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: divide by zero encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: overflow encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: invalid value encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
16:15:43 - cmdstanpy - INFO - Chain [1] start processing
16:15:44 - cmdstanpy - INFO - Chain [1] done processing
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: divide by zero encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: overflow encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: invalid value encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: divide by zero encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: overflow encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: invalid value encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: divide by zero encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: overflow encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: invalid value encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
16:15:44 - cmdstanpy - INFO - Chain [1] start processing
16:15:45 - cmdstanpy - INFO - Chain [1] done processing
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: divide by zero encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: overflow encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: invalid value encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: divide by zero encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: overflow encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: invalid value encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: divide by zero encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: overflow encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: invalid value encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
16:15:46 - cmdstanpy - INFO - Chain [1] start processing
16:15:48 - cmdstanpy - INFO - Chain [1] done processing
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: divide by zero encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: overflow encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: invalid value encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: divide by zero encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: overflow encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: invalid value encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: divide by zero encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: overflow encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: invalid value encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
16:15:49 - cmdstanpy - INFO - Chain [1] start processing
16:15:50 - cmdstanpy - INFO - Chain [1] done processing
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: divide by zero encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: overflow encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: invalid value encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: divide by zero encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: overflow encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: invalid value encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: divide by zero encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: overflow encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: invalid value encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
16:15:51 - cmdstanpy - INFO - Chain [1] start processing
16:15:51 - cmdstanpy - INFO - Chain [1] done processing
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: divide by zero encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: overflow encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: invalid value encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: divide by zero encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: overflow encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: invalid value encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: divide by zero encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: overflow encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: invalid value encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
16:15:52 - cmdstanpy - INFO - Chain [1] start processing
16:15:52 - cmdstanpy - INFO - Chain [1] done processing
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: divide by zero encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: overflow encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: invalid value encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: divide by zero encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: overflow encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: invalid value encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: divide by zero encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: overflow encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: invalid value encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
16:15:53 - cmdstanpy - INFO - Chain [1] start processing
16:15:53 - cmdstanpy - INFO - Chain [1] done processing

  0%|          | 0/8 [00:00<?, ?it/s]

16:15:53 - cmdstanpy - INFO - Chain [1] start processing
16:15:54 - cmdstanpy - INFO - Chain [1] done processing
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: divide by zero encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: overflow encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: invalid value encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: divide by zero encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: overflow encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: invalid value encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: divide by zero encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: overflow encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: invalid value encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
16:15:55 - cmdstanpy - INFO - Chain [1] start processing
16:15:55 - cmdstanpy - INFO - Chain [1] done processing
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: divide by zero encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: overflow encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: invalid value encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: divide by zero encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: overflow encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: invalid value encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: divide by zero encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: overflow encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: invalid value encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
16:15:56 - cmdstanpy - INFO - Chain [1] start processing
16:15:57 - cmdstanpy - INFO - Chain [1] done processing
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: divide by zero encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: overflow encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: invalid value encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: divide by zero encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: overflow encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: invalid value encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: divide by zero encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: overflow encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: invalid value encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
16:15:58 - cmdstanpy - INFO - Chain [1] start processing
16:15:59 - cmdstanpy - INFO - Chain [1] done processing
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: divide by zero encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: overflow encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: invalid value encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: divide by zero encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: overflow encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: invalid value encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: divide by zero encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: overflow encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: invalid value encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
16:16:00 - cmdstanpy - INFO - Chain [1] start processing
16:16:02 - cmdstanpy - INFO - Chain [1] done processing
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: divide by zero encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: overflow encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: invalid value encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: divide by zero encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: overflow encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: invalid value encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: divide by zero encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: overflow encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: invalid value encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
16:16:03 - cmdstanpy - INFO - Chain [1] start processing
16:16:04 - cmdstanpy - INFO - Chain [1] done processing
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: divide by zero encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: overflow encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: invalid value encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: divide by zero encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: overflow encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: invalid value encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: divide by zero encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: overflow encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: invalid value encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
16:16:05 - cmdstanpy - INFO - Chain [1] start processing
16:16:05 - cmdstanpy - INFO - Chain [1] done processing
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: divide by zero encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: overflow encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: invalid value encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: divide by zero encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: overflow encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: invalid value encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: divide by zero encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: overflow encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: invalid value encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
16:16:06 - cmdstanpy - INFO - Chain [1] start processing
16:16:06 - cmdstanpy - INFO - Chain [1] done processing
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: divide by zero encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: overflow encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: invalid value encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: divide by zero encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: overflow encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: invalid value encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: divide by zero encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: overflow encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: invalid value encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
16:16:07 - cmdstanpy - INFO - Chain [1] start processing
16:16:07 - cmdstanpy - INFO - Chain [1] done processing

  0%|          | 0/8 [00:00<?, ?it/s]

16:16:07 - cmdstanpy - INFO - Chain [1] start processing
16:16:08 - cmdstanpy - INFO - Chain [1] done processing
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: divide by zero encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: overflow encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: invalid value encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: divide by zero encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: overflow encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: invalid value encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: divide by zero encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: overflow encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: invalid value encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
16:16:09 - cmdstanpy - INFO - Chain [1] start processing
16:16:10 - cmdstanpy - INFO - Chain [1] done processing
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: divide by zero encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: overflow encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: invalid value encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: divide by zero encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: overflow encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: invalid value encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: divide by zero encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: overflow encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: invalid value encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
16:16:10 - cmdstanpy - INFO - Chain [1] start processing
16:16:11 - cmdstanpy - INFO - Chain [1] done processing
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: divide by zero encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: overflow encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: invalid value encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: divide by zero encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: overflow encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: invalid value encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: divide by zero encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: overflow encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: invalid value encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
16:16:12 - cmdstanpy - INFO - Chain [1] start processing
16:16:14 - cmdstanpy - INFO - Chain [1] done processing
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: divide by zero encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: overflow encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: invalid value encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: divide by zero encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: overflow encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: invalid value encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: divide by zero encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: overflow encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: invalid value encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
16:16:14 - cmdstanpy - INFO - Chain [1] start processing
16:16:16 - cmdstanpy - INFO - Chain [1] done processing
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: divide by zero encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: overflow encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: invalid value encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: divide by zero encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: overflow encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: invalid value encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: divide by zero encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: overflow encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: invalid value encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
16:16:17 - cmdstanpy - INFO - Chain [1] start processing
16:16:19 - cmdstanpy - INFO - Chain [1] done processing
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: divide by zero encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: overflow encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: invalid value encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: divide by zero encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: overflow encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: invalid value encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: divide by zero encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: overflow encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: invalid value encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
16:16:20 - cmdstanpy - INFO - Chain [1] start processing
16:16:20 - cmdstanpy - INFO - Chain [1] done processing
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: divide by zero encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: overflow encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: invalid value encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: divide by zero encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: overflow encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: invalid value encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: divide by zero encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: overflow encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: invalid value encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
16:16:20 - cmdstanpy - INFO - Chain [1] start processing
16:16:20 - cmdstanpy - INFO - Chain [1] done processing
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: divide by zero encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: overflow encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: invalid value encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: divide by zero encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: overflow encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: invalid value encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: divide by zero encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: overflow encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: invalid value encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
16:16:21 - cmdstanpy - INFO - Chain [1] start processing
16:16:21 - cmdstanpy - INFO - Chain [1] done processing

  0%|          | 0/8 [00:00<?, ?it/s]

16:16:22 - cmdstanpy - INFO - Chain [1] start processing
16:16:23 - cmdstanpy - INFO - Chain [1] done processing
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: divide by zero encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: overflow encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: invalid value encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: divide by zero encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: overflow encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: invalid value encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: divide by zero encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: overflow encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: invalid value encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
16:16:23 - cmdstanpy - INFO - Chain [1] start processing
16:16:24 - cmdstanpy - INFO - Chain [1] done processing
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: divide by zero encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: overflow encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: invalid value encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: divide by zero encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: overflow encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: invalid value encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: divide by zero encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: overflow encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: invalid value encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
16:16:25 - cmdstanpy - INFO - Chain [1] start processing
16:16:26 - cmdstanpy - INFO - Chain [1] done processing
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: divide by zero encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: overflow encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: invalid value encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: divide by zero encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: overflow encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: invalid value encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: divide by zero encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: overflow encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: invalid value encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
16:16:27 - cmdstanpy - INFO - Chain [1] start processing
16:16:28 - cmdstanpy - INFO - Chain [1] done processing
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: divide by zero encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: overflow encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: invalid value encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: divide by zero encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: overflow encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: invalid value encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: divide by zero encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: overflow encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: invalid value encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
16:16:29 - cmdstanpy - INFO - Chain [1] start processing
16:16:30 - cmdstanpy - INFO - Chain [1] done processing
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: divide by zero encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: overflow encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: invalid value encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: divide by zero encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: overflow encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: invalid value encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: divide by zero encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: overflow encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: invalid value encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
16:16:31 - cmdstanpy - INFO - Chain [1] start processing
16:16:33 - cmdstanpy - INFO - Chain [1] done processing
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: divide by zero encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: overflow encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: invalid value encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: divide by zero encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: overflow encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: invalid value encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: divide by zero encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: overflow encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: invalid value encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
16:16:33 - cmdstanpy - INFO - Chain [1] start processing
16:16:33 - cmdstanpy - INFO - Chain [1] done processing
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: divide by zero encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: overflow encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: invalid value encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: divide by zero encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: overflow encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: invalid value encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: divide by zero encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: overflow encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: invalid value encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
16:16:34 - cmdstanpy - INFO - Chain [1] start processing
16:16:34 - cmdstanpy - INFO - Chain [1] done processing
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: divide by zero encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: overflow encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: invalid value encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: divide by zero encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: overflow encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: invalid value encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: divide by zero encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: overflow encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: invalid value encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
16:16:35 - cmdstanpy - INFO - Chain [1] start processing
16:16:35 - cmdstanpy - INFO - Chain [1] done processing

  0%|          | 0/8 [00:00<?, ?it/s]

16:16:36 - cmdstanpy - INFO - Chain [1] start processing
16:16:36 - cmdstanpy - INFO - Chain [1] done processing
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: divide by zero encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: overflow encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: invalid value encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: divide by zero encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: overflow encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: invalid value encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: divide by zero encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: overflow encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: invalid value encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
16:16:37 - cmdstanpy - INFO - Chain [1] start processing
16:16:38 - cmdstanpy - INFO - Chain [1] done processing
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: divide by zero encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: overflow encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: invalid value encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: divide by zero encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: overflow encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: invalid value encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: divide by zero encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: overflow encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: invalid value encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
16:16:39 - cmdstanpy - INFO - Chain [1] start processing
16:16:40 - cmdstanpy - INFO - Chain [1] done processing
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: divide by zero encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: overflow encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: invalid value encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: divide by zero encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: overflow encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: invalid value encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: divide by zero encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: overflow encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: invalid value encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
16:16:41 - cmdstanpy - INFO - Chain [1] start processing
16:16:42 - cmdstanpy - INFO - Chain [1] done processing
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: divide by zero encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: overflow encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: invalid value encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: divide by zero encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: overflow encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: invalid value encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: divide by zero encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: overflow encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: invalid value encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
16:16:43 - cmdstanpy - INFO - Chain [1] start processing
16:16:44 - cmdstanpy - INFO - Chain [1] done processing
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: divide by zero encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: overflow encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: invalid value encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: divide by zero encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: overflow encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: invalid value encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: divide by zero encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: overflow encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: invalid value encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
16:16:45 - cmdstanpy - INFO - Chain [1] start processing
16:16:47 - cmdstanpy - INFO - Chain [1] done processing
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: divide by zero encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: overflow encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: invalid value encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: divide by zero encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: overflow encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: invalid value encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: divide by zero encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: overflow encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: invalid value encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
16:16:47 - cmdstanpy - INFO - Chain [1] start processing
16:16:47 - cmdstanpy - INFO - Chain [1] done processing
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: divide by zero encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: overflow encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: invalid value encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: divide by zero encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: overflow encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: invalid value encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: divide by zero encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: overflow encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: invalid value encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
16:16:48 - cmdstanpy - INFO - Chain [1] start processing
16:16:48 - cmdstanpy - INFO - Chain [1] done processing
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: divide by zero encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: overflow encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: invalid value encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: divide by zero encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: overflow encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: invalid value encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: divide by zero encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: overflow encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: invalid value encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
16:16:49 - cmdstanpy - INFO - Chain [1] start processing
16:16:49 - cmdstanpy - INFO - Chain [1] done processing

  0%|          | 0/8 [00:00<?, ?it/s]

16:16:50 - cmdstanpy - INFO - Chain [1] start processing
16:16:50 - cmdstanpy - INFO - Chain [1] done processing
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: divide by zero encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: overflow encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: invalid value encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: divide by zero encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: overflow encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: invalid value encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: divide by zero encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: overflow encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: invalid value encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
16:16:51 - cmdstanpy - INFO - Chain [1] start processing
16:16:52 - cmdstanpy - INFO - Chain [1] done processing
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: divide by zero encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: overflow encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: invalid value encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: divide by zero encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: overflow encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: invalid value encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: divide by zero encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: overflow encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: invalid value encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
16:16:53 - cmdstanpy - INFO - Chain [1] start processing
16:16:54 - cmdstanpy - INFO - Chain [1] done processing
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: divide by zero encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: overflow encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: invalid value encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: divide by zero encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: overflow encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: invalid value encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: divide by zero encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: overflow encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: invalid value encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
16:16:55 - cmdstanpy - INFO - Chain [1] start processing
16:16:56 - cmdstanpy - INFO - Chain [1] done processing
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: divide by zero encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: overflow encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: invalid value encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: divide by zero encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: overflow encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: invalid value encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: divide by zero encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: overflow encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: invalid value encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
16:16:57 - cmdstanpy - INFO - Chain [1] start processing
16:16:58 - cmdstanpy - INFO - Chain [1] done processing
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: divide by zero encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: overflow encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: invalid value encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: divide by zero encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: overflow encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: invalid value encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: divide by zero encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: overflow encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: invalid value encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
16:16:59 - cmdstanpy - INFO - Chain [1] start processing
16:17:01 - cmdstanpy - INFO - Chain [1] done processing
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: divide by zero encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: overflow encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: invalid value encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: divide by zero encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: overflow encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: invalid value encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: divide by zero encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: overflow encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: invalid value encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
16:17:01 - cmdstanpy - INFO - Chain [1] start processing
16:17:01 - cmdstanpy - INFO - Chain [1] done processing
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: divide by zero encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: overflow encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: invalid value encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: divide by zero encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: overflow encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: invalid value encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: divide by zero encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: overflow encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: invalid value encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
16:17:02 - cmdstanpy - INFO - Chain [1] start processing
16:17:02 - cmdstanpy - INFO - Chain [1] done processing
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: divide by zero encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: overflow encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: invalid value encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: divide by zero encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: overflow encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: invalid value encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: divide by zero encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: overflow encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: invalid value encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
16:17:03 - cmdstanpy - INFO - Chain [1] start processing
16:17:03 - cmdstanpy - INFO - Chain [1] done processing

  0%|          | 0/8 [00:00<?, ?it/s]

16:17:04 - cmdstanpy - INFO - Chain [1] start processing
16:17:04 - cmdstanpy - INFO - Chain [1] done processing
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: divide by zero encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: overflow encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: invalid value encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: divide by zero encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: overflow encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: invalid value encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: divide by zero encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: overflow encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: invalid value encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
16:17:05 - cmdstanpy - INFO - Chain [1] start processing
16:17:06 - cmdstanpy - INFO - Chain [1] done processing
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: divide by zero encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: overflow encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: invalid value encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: divide by zero encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: overflow encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: invalid value encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: divide by zero encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: overflow encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: invalid value encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
16:17:07 - cmdstanpy - INFO - Chain [1] start processing
16:17:08 - cmdstanpy - INFO - Chain [1] done processing
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: divide by zero encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: overflow encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: invalid value encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: divide by zero encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: overflow encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: invalid value encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: divide by zero encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: overflow encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: invalid value encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
16:17:09 - cmdstanpy - INFO - Chain [1] start processing
16:17:09 - cmdstanpy - INFO - Chain [1] done processing
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: divide by zero encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: overflow encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: invalid value encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: divide by zero encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: overflow encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: invalid value encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: divide by zero encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: overflow encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: invalid value encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
16:17:10 - cmdstanpy - INFO - Chain [1] start processing
16:17:12 - cmdstanpy - INFO - Chain [1] done processing
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: divide by zero encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: overflow encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: invalid value encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: divide by zero encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: overflow encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: invalid value encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: divide by zero encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: overflow encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: invalid value encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
16:17:12 - cmdstanpy - INFO - Chain [1] start processing
16:17:14 - cmdstanpy - INFO - Chain [1] done processing
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: divide by zero encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: overflow encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: invalid value encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: divide by zero encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: overflow encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: invalid value encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: divide by zero encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: overflow encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: invalid value encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
16:17:15 - cmdstanpy - INFO - Chain [1] start processing
16:17:15 - cmdstanpy - INFO - Chain [1] done processing
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: divide by zero encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: overflow encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: invalid value encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: divide by zero encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: overflow encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: invalid value encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: divide by zero encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: overflow encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: invalid value encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
16:17:15 - cmdstanpy - INFO - Chain [1] start processing
16:17:16 - cmdstanpy - INFO - Chain [1] done processing
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: divide by zero encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: overflow encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: invalid value encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: divide by zero encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: overflow encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: invalid value encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: divide by zero encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: overflow encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: invalid value encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
16:17:16 - cmdstanpy - INFO - Chain [1] start processing
16:17:16 - cmdstanpy - INFO - Chain [1] done processing

  0%|          | 0/8 [00:00<?, ?it/s]

16:17:17 - cmdstanpy - INFO - Chain [1] start processing
16:17:18 - cmdstanpy - INFO - Chain [1] done processing
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: divide by zero encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: overflow encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: invalid value encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: divide by zero encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: overflow encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: invalid value encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: divide by zero encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: overflow encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: invalid value encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
16:17:18 - cmdstanpy - INFO - Chain [1] start processing
16:17:19 - cmdstanpy - INFO - Chain [1] done processing
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: divide by zero encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: overflow encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: invalid value encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: divide by zero encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: overflow encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: invalid value encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: divide by zero encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: overflow encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: invalid value encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
16:17:20 - cmdstanpy - INFO - Chain [1] start processing
16:17:21 - cmdstanpy - INFO - Chain [1] done processing
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: divide by zero encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: overflow encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: invalid value encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: divide by zero encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: overflow encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: invalid value encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: divide by zero encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: overflow encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: invalid value encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
16:17:22 - cmdstanpy - INFO - Chain [1] start processing
16:17:23 - cmdstanpy - INFO - Chain [1] done processing
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: divide by zero encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: overflow encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: invalid value encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: divide by zero encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: overflow encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: invalid value encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: divide by zero encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: overflow encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: invalid value encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
16:17:24 - cmdstanpy - INFO - Chain [1] start processing
16:17:25 - cmdstanpy - INFO - Chain [1] done processing
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: divide by zero encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: overflow encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: invalid value encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: divide by zero encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: overflow encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: invalid value encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: divide by zero encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: overflow encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: invalid value encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
16:17:26 - cmdstanpy - INFO - Chain [1] start processing
16:17:28 - cmdstanpy - INFO - Chain [1] done processing
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: divide by zero encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: overflow encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: invalid value encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: divide by zero encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: overflow encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: invalid value encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: divide by zero encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: overflow encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: invalid value encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
16:17:29 - cmdstanpy - INFO - Chain [1] start processing
16:17:29 - cmdstanpy - INFO - Chain [1] done processing
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: divide by zero encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: overflow encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: invalid value encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: divide by zero encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: overflow encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: invalid value encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: divide by zero encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: overflow encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: invalid value encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
16:17:29 - cmdstanpy - INFO - Chain [1] start processing
16:17:30 - cmdstanpy - INFO - Chain [1] done processing
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: divide by zero encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: overflow encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: invalid value encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: divide by zero encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: overflow encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: invalid value encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: divide by zero encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: overflow encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: invalid value encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
16:17:30 - cmdstanpy - INFO - Chain [1] start processing
16:17:30 - cmdstanpy - INFO - Chain [1] done processing

  0%|          | 0/8 [00:00<?, ?it/s]

16:17:31 - cmdstanpy - INFO - Chain [1] start processing
16:17:32 - cmdstanpy - INFO - Chain [1] done processing
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: divide by zero encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: overflow encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: invalid value encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: divide by zero encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: overflow encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: invalid value encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: divide by zero encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: overflow encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: invalid value encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
16:17:32 - cmdstanpy - INFO - Chain [1] start processing
16:17:33 - cmdstanpy - INFO - Chain [1] done processing
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: divide by zero encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: overflow encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: invalid value encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: divide by zero encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: overflow encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: invalid value encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: divide by zero encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: overflow encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: invalid value encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
16:17:34 - cmdstanpy - INFO - Chain [1] start processing
16:17:35 - cmdstanpy - INFO - Chain [1] done processing
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: divide by zero encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: overflow encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: invalid value encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: divide by zero encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: overflow encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: invalid value encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: divide by zero encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: overflow encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: invalid value encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
16:17:36 - cmdstanpy - INFO - Chain [1] start processing
16:17:38 - cmdstanpy - INFO - Chain [1] done processing
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: divide by zero encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: overflow encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: invalid value encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: divide by zero encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: overflow encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: invalid value encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: divide by zero encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: overflow encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: invalid value encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
16:17:38 - cmdstanpy - INFO - Chain [1] start processing
16:17:40 - cmdstanpy - INFO - Chain [1] done processing
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: divide by zero encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: overflow encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: invalid value encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: divide by zero encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: overflow encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: invalid value encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: divide by zero encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: overflow encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: invalid value encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
16:17:41 - cmdstanpy - INFO - Chain [1] start processing
16:17:43 - cmdstanpy - INFO - Chain [1] done processing
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: divide by zero encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: overflow encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: invalid value encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: divide by zero encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: overflow encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: invalid value encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: divide by zero encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: overflow encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: invalid value encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
16:17:44 - cmdstanpy - INFO - Chain [1] start processing
16:17:44 - cmdstanpy - INFO - Chain [1] done processing
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: divide by zero encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: overflow encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: invalid value encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: divide by zero encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: overflow encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: invalid value encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: divide by zero encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: overflow encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: invalid value encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
16:17:45 - cmdstanpy - INFO - Chain [1] start processing
16:17:45 - cmdstanpy - INFO - Chain [1] done processing
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: divide by zero encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: overflow encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: invalid value encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: divide by zero encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: overflow encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: invalid value encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: divide by zero encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: overflow encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: invalid value encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
16:17:46 - cmdstanpy - INFO - Chain [1] start processing
16:17:46 - cmdstanpy - INFO - Chain [1] done processing

  0%|          | 0/8 [00:00<?, ?it/s]

16:17:46 - cmdstanpy - INFO - Chain [1] start processing
16:17:47 - cmdstanpy - INFO - Chain [1] done processing
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: divide by zero encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: overflow encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: invalid value encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: divide by zero encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: overflow encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: invalid value encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: divide by zero encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: overflow encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: invalid value encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
16:17:48 - cmdstanpy - INFO - Chain [1] start processing
16:17:49 - cmdstanpy - INFO - Chain [1] done processing
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: divide by zero encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: overflow encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: invalid value encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: divide by zero encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: overflow encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: invalid value encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: divide by zero encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: overflow encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: invalid value encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
16:17:50 - cmdstanpy - INFO - Chain [1] start processing
16:17:51 - cmdstanpy - INFO - Chain [1] done processing
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: divide by zero encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: overflow encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: invalid value encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: divide by zero encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: overflow encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: invalid value encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: divide by zero encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: overflow encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: invalid value encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
16:17:52 - cmdstanpy - INFO - Chain [1] start processing
16:17:54 - cmdstanpy - INFO - Chain [1] done processing
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: divide by zero encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: overflow encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: invalid value encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: divide by zero encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: overflow encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: invalid value encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: divide by zero encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: overflow encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: invalid value encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
16:17:54 - cmdstanpy - INFO - Chain [1] start processing
16:17:57 - cmdstanpy - INFO - Chain [1] done processing
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: divide by zero encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: overflow encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: invalid value encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: divide by zero encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: overflow encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: invalid value encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: divide by zero encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: overflow encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: invalid value encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
16:17:58 - cmdstanpy - INFO - Chain [1] start processing
16:18:00 - cmdstanpy - INFO - Chain [1] done processing
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: divide by zero encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: overflow encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: invalid value encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: divide by zero encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: overflow encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: invalid value encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: divide by zero encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: overflow encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: invalid value encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
16:18:01 - cmdstanpy - INFO - Chain [1] start processing
16:18:01 - cmdstanpy - INFO - Chain [1] done processing
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: divide by zero encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: overflow encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: invalid value encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: divide by zero encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: overflow encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: invalid value encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: divide by zero encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: overflow encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: invalid value encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
16:18:02 - cmdstanpy - INFO - Chain [1] start processing
16:18:02 - cmdstanpy - INFO - Chain [1] done processing
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: divide by zero encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: overflow encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: invalid value encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: divide by zero encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: overflow encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: invalid value encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: divide by zero encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: overflow encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: invalid value encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
16:18:03 - cmdstanpy - INFO - Chain [1] start processing
16:18:03 - cmdstanpy - INFO - Chain [1] done processing

  0%|          | 0/8 [00:00<?, ?it/s]

16:18:03 - cmdstanpy - INFO - Chain [1] start processing
16:18:04 - cmdstanpy - INFO - Chain [1] done processing
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: divide by zero encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: overflow encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: invalid value encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: divide by zero encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: overflow encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: invalid value encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: divide by zero encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: overflow encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: invalid value encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
16:18:05 - cmdstanpy - INFO - Chain [1] start processing
16:18:06 - cmdstanpy - INFO - Chain [1] done processing
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: divide by zero encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: overflow encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: invalid value encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: divide by zero encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: overflow encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: invalid value encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: divide by zero encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: overflow encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: invalid value encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
16:18:07 - cmdstanpy - INFO - Chain [1] start processing
16:18:08 - cmdstanpy - INFO - Chain [1] done processing
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: divide by zero encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: overflow encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: invalid value encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: divide by zero encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: overflow encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: invalid value encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: divide by zero encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: overflow encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: invalid value encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
16:18:08 - cmdstanpy - INFO - Chain [1] start processing
16:18:10 - cmdstanpy - INFO - Chain [1] done processing
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: divide by zero encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: overflow encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: invalid value encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: divide by zero encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: overflow encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: invalid value encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: divide by zero encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: overflow encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: invalid value encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
16:18:11 - cmdstanpy - INFO - Chain [1] start processing
16:18:12 - cmdstanpy - INFO - Chain [1] done processing
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: divide by zero encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: overflow encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: invalid value encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: divide by zero encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: overflow encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: invalid value encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: divide by zero encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: overflow encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: invalid value encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
16:18:13 - cmdstanpy - INFO - Chain [1] start processing
16:18:15 - cmdstanpy - INFO - Chain [1] done processing
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: divide by zero encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: overflow encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: invalid value encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: divide by zero encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: overflow encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: invalid value encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: divide by zero encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: overflow encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: invalid value encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
16:18:16 - cmdstanpy - INFO - Chain [1] start processing
16:18:16 - cmdstanpy - INFO - Chain [1] done processing
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: divide by zero encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: overflow encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: invalid value encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: divide by zero encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: overflow encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: invalid value encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: divide by zero encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: overflow encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: invalid value encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
16:18:17 - cmdstanpy - INFO - Chain [1] start processing
16:18:17 - cmdstanpy - INFO - Chain [1] done processing
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: divide by zero encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: overflow encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: invalid value encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: divide by zero encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: overflow encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: invalid value encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: divide by zero encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: overflow encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: invalid value encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
16:18:18 - cmdstanpy - INFO - Chain [1] start processing
16:18:18 - cmdstanpy - INFO - Chain [1] done processing

  0%|          | 0/8 [00:00<?, ?it/s]

16:18:18 - cmdstanpy - INFO - Chain [1] start processing
16:18:19 - cmdstanpy - INFO - Chain [1] done processing
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: divide by zero encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: overflow encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: invalid value encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: divide by zero encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: overflow encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: invalid value encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: divide by zero encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: overflow encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: invalid value encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
16:18:20 - cmdstanpy - INFO - Chain [1] start processing
16:18:21 - cmdstanpy - INFO - Chain [1] done processing
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: divide by zero encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: overflow encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: invalid value encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: divide by zero encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: overflow encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: invalid value encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: divide by zero encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: overflow encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: invalid value encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
16:18:22 - cmdstanpy - INFO - Chain [1] start processing
16:18:23 - cmdstanpy - INFO - Chain [1] done processing
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: divide by zero encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: overflow encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: invalid value encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: divide by zero encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: overflow encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: invalid value encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: divide by zero encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: overflow encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: invalid value encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
16:18:24 - cmdstanpy - INFO - Chain [1] start processing
16:18:25 - cmdstanpy - INFO - Chain [1] done processing
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: divide by zero encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: overflow encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: invalid value encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: divide by zero encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: overflow encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: invalid value encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: divide by zero encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: overflow encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: invalid value encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
16:18:26 - cmdstanpy - INFO - Chain [1] start processing
16:18:27 - cmdstanpy - INFO - Chain [1] done processing
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: divide by zero encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: overflow encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: invalid value encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: divide by zero encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: overflow encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: invalid value encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: divide by zero encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: overflow encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: invalid value encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
16:18:28 - cmdstanpy - INFO - Chain [1] start processing
16:18:30 - cmdstanpy - INFO - Chain [1] done processing
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: divide by zero encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: overflow encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: invalid value encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: divide by zero encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: overflow encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: invalid value encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: divide by zero encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: overflow encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: invalid value encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
16:18:31 - cmdstanpy - INFO - Chain [1] start processing
16:18:31 - cmdstanpy - INFO - Chain [1] done processing
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: divide by zero encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: overflow encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: invalid value encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: divide by zero encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: overflow encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: invalid value encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: divide by zero encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: overflow encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: invalid value encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
16:18:32 - cmdstanpy - INFO - Chain [1] start processing
16:18:32 - cmdstanpy - INFO - Chain [1] done processing
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: divide by zero encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: overflow encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: invalid value encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: divide by zero encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: overflow encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: invalid value encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: divide by zero encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: overflow encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: invalid value encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
16:18:33 - cmdstanpy - INFO - Chain [1] start processing
16:18:33 - cmdstanpy - INFO - Chain [1] done processing

  0%|          | 0/8 [00:00<?, ?it/s]

16:18:33 - cmdstanpy - INFO - Chain [1] start processing
16:18:34 - cmdstanpy - INFO - Chain [1] done processing
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: divide by zero encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: overflow encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: invalid value encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: divide by zero encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: overflow encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: invalid value encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: divide by zero encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: overflow encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: invalid value encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
16:18:35 - cmdstanpy - INFO - Chain [1] start processing
16:18:36 - cmdstanpy - INFO - Chain [1] done processing
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: divide by zero encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: overflow encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: invalid value encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: divide by zero encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: overflow encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: invalid value encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: divide by zero encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: overflow encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: invalid value encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
16:18:37 - cmdstanpy - INFO - Chain [1] start processing
16:18:38 - cmdstanpy - INFO - Chain [1] done processing
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: divide by zero encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: overflow encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: invalid value encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: divide by zero encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: overflow encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: invalid value encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: divide by zero encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: overflow encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: invalid value encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
16:18:39 - cmdstanpy - INFO - Chain [1] start processing
16:18:40 - cmdstanpy - INFO - Chain [1] done processing
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: divide by zero encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: overflow encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: invalid value encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: divide by zero encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: overflow encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: invalid value encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: divide by zero encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: overflow encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: invalid value encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
16:18:41 - cmdstanpy - INFO - Chain [1] start processing
16:18:43 - cmdstanpy - INFO - Chain [1] done processing
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: divide by zero encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: overflow encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: invalid value encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: divide by zero encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: overflow encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: invalid value encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: divide by zero encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: overflow encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: invalid value encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
16:18:44 - cmdstanpy - INFO - Chain [1] start processing
16:18:46 - cmdstanpy - INFO - Chain [1] done processing
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: divide by zero encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: overflow encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: invalid value encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: divide by zero encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: overflow encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: invalid value encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: divide by zero encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: overflow encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: invalid value encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
16:18:47 - cmdstanpy - INFO - Chain [1] start processing
16:18:47 - cmdstanpy - INFO - Chain [1] done processing
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: divide by zero encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: overflow encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: invalid value encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: divide by zero encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: overflow encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: invalid value encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: divide by zero encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: overflow encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: invalid value encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
16:18:48 - cmdstanpy - INFO - Chain [1] start processing
16:18:48 - cmdstanpy - INFO - Chain [1] done processing
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: divide by zero encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: overflow encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: invalid value encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: divide by zero encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: overflow encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: invalid value encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: divide by zero encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: overflow encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: invalid value encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
16:18:49 - cmdstanpy - INFO - Chain [1] start processing
16:18:49 - cmdstanpy - INFO - Chain [1] done processing

  0%|          | 0/8 [00:00<?, ?it/s]

16:18:49 - cmdstanpy - INFO - Chain [1] start processing
16:18:50 - cmdstanpy - INFO - Chain [1] done processing
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: divide by zero encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: overflow encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: invalid value encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: divide by zero encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: overflow encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: invalid value encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: divide by zero encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: overflow encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: invalid value encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
16:18:51 - cmdstanpy - INFO - Chain [1] start processing
16:18:52 - cmdstanpy - INFO - Chain [1] done processing
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: divide by zero encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: overflow encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: invalid value encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: divide by zero encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: overflow encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: invalid value encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: divide by zero encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: overflow encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: invalid value encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
16:18:53 - cmdstanpy - INFO - Chain [1] start processing
16:18:54 - cmdstanpy - INFO - Chain [1] done processing
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: divide by zero encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: overflow encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: invalid value encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: divide by zero encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: overflow encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: invalid value encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: divide by zero encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: overflow encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: invalid value encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
16:18:55 - cmdstanpy - INFO - Chain [1] start processing
16:18:56 - cmdstanpy - INFO - Chain [1] done processing
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: divide by zero encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: overflow encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: invalid value encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: divide by zero encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: overflow encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: invalid value encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: divide by zero encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: overflow encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: invalid value encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
16:18:57 - cmdstanpy - INFO - Chain [1] start processing
16:18:59 - cmdstanpy - INFO - Chain [1] done processing
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: divide by zero encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: overflow encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: invalid value encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: divide by zero encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: overflow encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: invalid value encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: divide by zero encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: overflow encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: invalid value encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
16:19:00 - cmdstanpy - INFO - Chain [1] start processing
16:19:01 - cmdstanpy - INFO - Chain [1] done processing
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: divide by zero encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: overflow encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: invalid value encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: divide by zero encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: overflow encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: invalid value encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: divide by zero encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: overflow encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: invalid value encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
16:19:02 - cmdstanpy - INFO - Chain [1] start processing
16:19:02 - cmdstanpy - INFO - Chain [1] done processing
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: divide by zero encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: overflow encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: invalid value encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: divide by zero encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: overflow encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: invalid value encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: divide by zero encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: overflow encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: invalid value encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
16:19:03 - cmdstanpy - INFO - Chain [1] start processing
16:19:03 - cmdstanpy - INFO - Chain [1] done processing
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: divide by zero encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: overflow encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: invalid value encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: divide by zero encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: overflow encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: invalid value encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: divide by zero encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: overflow encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: invalid value encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
16:19:04 - cmdstanpy - INFO - Chain [1] start processing
16:19:04 - cmdstanpy - INFO - Chain [1] done processing

  0%|          | 0/8 [00:00<?, ?it/s]

16:19:04 - cmdstanpy - INFO - Chain [1] start processing
16:19:05 - cmdstanpy - INFO - Chain [1] done processing
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: divide by zero encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: overflow encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: invalid value encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: divide by zero encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: overflow encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: invalid value encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: divide by zero encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: overflow encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: invalid value encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
16:19:06 - cmdstanpy - INFO - Chain [1] start processing
16:19:07 - cmdstanpy - INFO - Chain [1] done processing
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: divide by zero encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: overflow encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: invalid value encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: divide by zero encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: overflow encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: invalid value encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: divide by zero encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: overflow encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: invalid value encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
16:19:08 - cmdstanpy - INFO - Chain [1] start processing
16:19:09 - cmdstanpy - INFO - Chain [1] done processing
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: divide by zero encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: overflow encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: invalid value encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: divide by zero encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: overflow encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: invalid value encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: divide by zero encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: overflow encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: invalid value encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
16:19:10 - cmdstanpy - INFO - Chain [1] start processing
16:19:11 - cmdstanpy - INFO - Chain [1] done processing
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: divide by zero encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: overflow encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: invalid value encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: divide by zero encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: overflow encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: invalid value encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: divide by zero encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: overflow encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: invalid value encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
16:19:12 - cmdstanpy - INFO - Chain [1] start processing
16:19:14 - cmdstanpy - INFO - Chain [1] done processing
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: divide by zero encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: overflow encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: invalid value encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: divide by zero encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: overflow encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: invalid value encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: divide by zero encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: overflow encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: invalid value encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
16:19:15 - cmdstanpy - INFO - Chain [1] start processing
16:19:16 - cmdstanpy - INFO - Chain [1] done processing
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: divide by zero encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: overflow encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: invalid value encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: divide by zero encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: overflow encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: invalid value encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: divide by zero encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: overflow encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: invalid value encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
16:19:17 - cmdstanpy - INFO - Chain [1] start processing
16:19:17 - cmdstanpy - INFO - Chain [1] done processing
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: divide by zero encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: overflow encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: invalid value encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: divide by zero encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: overflow encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: invalid value encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: divide by zero encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: overflow encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: invalid value encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
16:19:18 - cmdstanpy - INFO - Chain [1] start processing
16:19:18 - cmdstanpy - INFO - Chain [1] done processing
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: divide by zero encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: overflow encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: invalid value encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: divide by zero encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: overflow encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: invalid value encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: divide by zero encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: overflow encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: invalid value encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
16:19:19 - cmdstanpy - INFO - Chain [1] start processing
16:19:19 - cmdstanpy - INFO - Chain [1] done processing

  0%|          | 0/8 [00:00<?, ?it/s]

16:19:20 - cmdstanpy - INFO - Chain [1] start processing
16:19:20 - cmdstanpy - INFO - Chain [1] done processing
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: divide by zero encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: overflow encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: invalid value encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: divide by zero encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: overflow encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: invalid value encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: divide by zero encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: overflow encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: invalid value encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
16:19:21 - cmdstanpy - INFO - Chain [1] start processing
16:19:22 - cmdstanpy - INFO - Chain [1] done processing
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: divide by zero encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: overflow encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: invalid value encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: divide by zero encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: overflow encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: invalid value encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: divide by zero encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: overflow encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: invalid value encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
16:19:23 - cmdstanpy - INFO - Chain [1] start processing
16:19:24 - cmdstanpy - INFO - Chain [1] done processing
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: divide by zero encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: overflow encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: invalid value encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: divide by zero encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: overflow encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: invalid value encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: divide by zero encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: overflow encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: invalid value encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
16:19:25 - cmdstanpy - INFO - Chain [1] start processing
16:19:26 - cmdstanpy - INFO - Chain [1] done processing
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: divide by zero encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: overflow encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: invalid value encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: divide by zero encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: overflow encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: invalid value encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: divide by zero encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: overflow encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: invalid value encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
16:19:27 - cmdstanpy - INFO - Chain [1] start processing
16:19:29 - cmdstanpy - INFO - Chain [1] done processing
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: divide by zero encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: overflow encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: invalid value encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: divide by zero encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: overflow encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: invalid value encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: divide by zero encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: overflow encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: invalid value encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
16:19:30 - cmdstanpy - INFO - Chain [1] start processing
16:19:31 - cmdstanpy - INFO - Chain [1] done processing
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: divide by zero encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: overflow encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: invalid value encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: divide by zero encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: overflow encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: invalid value encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: divide by zero encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: overflow encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: invalid value encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
16:19:32 - cmdstanpy - INFO - Chain [1] start processing
16:19:32 - cmdstanpy - INFO - Chain [1] done processing
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: divide by zero encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: overflow encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: invalid value encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: divide by zero encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: overflow encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: invalid value encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: divide by zero encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: overflow encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: invalid value encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
16:19:33 - cmdstanpy - INFO - Chain [1] start processing
16:19:33 - cmdstanpy - INFO - Chain [1] done processing
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: divide by zero encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: overflow encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: invalid value encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: divide by zero encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: overflow encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: invalid value encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: divide by zero encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: overflow encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: invalid value encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
16:19:34 - cmdstanpy - INFO - Chain [1] start processing
16:19:34 - cmdstanpy - INFO - Chain [1] done processing

  0%|          | 0/8 [00:00<?, ?it/s]

16:19:34 - cmdstanpy - INFO - Chain [1] start processing
16:19:35 - cmdstanpy - INFO - Chain [1] done processing
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: divide by zero encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: overflow encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: invalid value encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: divide by zero encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: overflow encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: invalid value encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: divide by zero encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: overflow encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: invalid value encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
16:19:36 - cmdstanpy - INFO - Chain [1] start processing
16:19:37 - cmdstanpy - INFO - Chain [1] done processing
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: divide by zero encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: overflow encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: invalid value encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: divide by zero encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: overflow encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: invalid value encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: divide by zero encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: overflow encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: invalid value encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
16:19:38 - cmdstanpy - INFO - Chain [1] start processing
16:19:39 - cmdstanpy - INFO - Chain [1] done processing
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: divide by zero encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: overflow encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: invalid value encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: divide by zero encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: overflow encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: invalid value encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: divide by zero encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: overflow encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: invalid value encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
16:19:40 - cmdstanpy - INFO - Chain [1] start processing
16:19:41 - cmdstanpy - INFO - Chain [1] done processing
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: divide by zero encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: overflow encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: invalid value encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: divide by zero encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: overflow encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: invalid value encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: divide by zero encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: overflow encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: invalid value encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
16:19:42 - cmdstanpy - INFO - Chain [1] start processing
16:19:44 - cmdstanpy - INFO - Chain [1] done processing
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: divide by zero encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: overflow encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: invalid value encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: divide by zero encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: overflow encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: invalid value encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: divide by zero encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: overflow encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: invalid value encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
16:19:45 - cmdstanpy - INFO - Chain [1] start processing
16:19:47 - cmdstanpy - INFO - Chain [1] done processing
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: divide by zero encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: overflow encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: invalid value encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: divide by zero encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: overflow encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: invalid value encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: divide by zero encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: overflow encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: invalid value encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
16:19:48 - cmdstanpy - INFO - Chain [1] start processing
16:19:48 - cmdstanpy - INFO - Chain [1] done processing
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: divide by zero encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: overflow encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: invalid value encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: divide by zero encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: overflow encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: invalid value encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: divide by zero encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: overflow encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: invalid value encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
16:19:49 - cmdstanpy - INFO - Chain [1] start processing
16:19:49 - cmdstanpy - INFO - Chain [1] done processing
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: divide by zero encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: overflow encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: invalid value encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: divide by zero encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: overflow encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: invalid value encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: divide by zero encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: overflow encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: invalid value encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
16:19:50 - cmdstanpy - INFO - Chain [1] start processing
16:19:50 - cmdstanpy - INFO - Chain [1] done processing

  0%|          | 0/8 [00:00<?, ?it/s]

16:19:50 - cmdstanpy - INFO - Chain [1] start processing
16:19:51 - cmdstanpy - INFO - Chain [1] done processing
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: divide by zero encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: overflow encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: invalid value encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: divide by zero encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: overflow encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: invalid value encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: divide by zero encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: overflow encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: invalid value encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
16:19:52 - cmdstanpy - INFO - Chain [1] start processing
16:19:53 - cmdstanpy - INFO - Chain [1] done processing
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: divide by zero encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: overflow encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: invalid value encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: divide by zero encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: overflow encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: invalid value encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: divide by zero encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: overflow encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: invalid value encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
16:19:54 - cmdstanpy - INFO - Chain [1] start processing
16:19:55 - cmdstanpy - INFO - Chain [1] done processing
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: divide by zero encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: overflow encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: invalid value encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: divide by zero encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: overflow encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: invalid value encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: divide by zero encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: overflow encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: invalid value encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
16:19:56 - cmdstanpy - INFO - Chain [1] start processing
16:19:58 - cmdstanpy - INFO - Chain [1] done processing
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: divide by zero encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: overflow encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: invalid value encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: divide by zero encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: overflow encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: invalid value encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: divide by zero encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: overflow encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: invalid value encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
16:19:59 - cmdstanpy - INFO - Chain [1] start processing
16:20:01 - cmdstanpy - INFO - Chain [1] done processing
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: divide by zero encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: overflow encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: invalid value encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: divide by zero encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: overflow encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: invalid value encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: divide by zero encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: overflow encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: invalid value encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
16:20:02 - cmdstanpy - INFO - Chain [1] start processing
16:20:04 - cmdstanpy - INFO - Chain [1] done processing
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: divide by zero encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: overflow encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: invalid value encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: divide by zero encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: overflow encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: invalid value encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: divide by zero encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: overflow encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: invalid value encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
16:20:05 - cmdstanpy - INFO - Chain [1] start processing
16:20:05 - cmdstanpy - INFO - Chain [1] done processing
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: divide by zero encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: overflow encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: invalid value encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: divide by zero encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: overflow encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: invalid value encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: divide by zero encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: overflow encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: invalid value encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
16:20:06 - cmdstanpy - INFO - Chain [1] start processing
16:20:06 - cmdstanpy - INFO - Chain [1] done processing
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: divide by zero encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: overflow encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: invalid value encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: divide by zero encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: overflow encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: invalid value encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: divide by zero encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: overflow encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: invalid value encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
16:20:07 - cmdstanpy - INFO - Chain [1] start processing
16:20:07 - cmdstanpy - INFO - Chain [1] done processing

  0%|          | 0/8 [00:00<?, ?it/s]

16:20:07 - cmdstanpy - INFO - Chain [1] start processing
16:20:08 - cmdstanpy - INFO - Chain [1] done processing
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: divide by zero encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: overflow encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: invalid value encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: divide by zero encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: overflow encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: invalid value encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: divide by zero encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: overflow encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: invalid value encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
16:20:09 - cmdstanpy - INFO - Chain [1] start processing
16:20:11 - cmdstanpy - INFO - Chain [1] done processing
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: divide by zero encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: overflow encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: invalid value encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: divide by zero encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: overflow encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: invalid value encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: divide by zero encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: overflow encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: invalid value encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
16:20:11 - cmdstanpy - INFO - Chain [1] start processing
16:20:12 - cmdstanpy - INFO - Chain [1] done processing
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: divide by zero encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: overflow encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: invalid value encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: divide by zero encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: overflow encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: invalid value encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: divide by zero encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: overflow encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: invalid value encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
16:20:13 - cmdstanpy - INFO - Chain [1] start processing
16:20:15 - cmdstanpy - INFO - Chain [1] done processing
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: divide by zero encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: overflow encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: invalid value encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: divide by zero encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: overflow encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: invalid value encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: divide by zero encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: overflow encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: invalid value encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
16:20:16 - cmdstanpy - INFO - Chain [1] start processing
16:20:17 - cmdstanpy - INFO - Chain [1] done processing
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: divide by zero encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: overflow encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: invalid value encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: divide by zero encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: overflow encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: invalid value encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: divide by zero encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: overflow encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: invalid value encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
16:20:18 - cmdstanpy - INFO - Chain [1] start processing
16:20:20 - cmdstanpy - INFO - Chain [1] done processing
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: divide by zero encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: overflow encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: invalid value encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: divide by zero encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: overflow encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: invalid value encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: divide by zero encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: overflow encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: invalid value encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
16:20:21 - cmdstanpy - INFO - Chain [1] start processing
16:20:21 - cmdstanpy - INFO - Chain [1] done processing
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: divide by zero encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: overflow encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: invalid value encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: divide by zero encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: overflow encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: invalid value encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: divide by zero encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: overflow encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: invalid value encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
16:20:22 - cmdstanpy - INFO - Chain [1] start processing
16:20:22 - cmdstanpy - INFO - Chain [1] done processing
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: divide by zero encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: overflow encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: invalid value encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: divide by zero encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: overflow encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: invalid value encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: divide by zero encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: overflow encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: invalid value encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
16:20:23 - cmdstanpy - INFO - Chain [1] start processing
16:20:23 - cmdstanpy - INFO - Chain [1] done processing

  0%|          | 0/8 [00:00<?, ?it/s]

16:20:23 - cmdstanpy - INFO - Chain [1] start processing
16:20:24 - cmdstanpy - INFO - Chain [1] done processing
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: divide by zero encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: overflow encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: invalid value encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: divide by zero encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: overflow encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: invalid value encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: divide by zero encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: overflow encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: invalid value encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
16:20:25 - cmdstanpy - INFO - Chain [1] start processing
16:20:26 - cmdstanpy - INFO - Chain [1] done processing
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: divide by zero encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: overflow encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: invalid value encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: divide by zero encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: overflow encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: invalid value encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: divide by zero encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: overflow encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: invalid value encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
16:20:27 - cmdstanpy - INFO - Chain [1] start processing
16:20:29 - cmdstanpy - INFO - Chain [1] done processing
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: divide by zero encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: overflow encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: invalid value encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: divide by zero encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: overflow encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: invalid value encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: divide by zero encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: overflow encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: invalid value encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
16:20:29 - cmdstanpy - INFO - Chain [1] start processing
16:20:31 - cmdstanpy - INFO - Chain [1] done processing
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: divide by zero encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: overflow encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: invalid value encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: divide by zero encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: overflow encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: invalid value encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: divide by zero encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: overflow encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: invalid value encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
16:20:32 - cmdstanpy - INFO - Chain [1] start processing
16:20:33 - cmdstanpy - INFO - Chain [1] done processing
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: divide by zero encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: overflow encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: invalid value encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: divide by zero encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: overflow encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: invalid value encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: divide by zero encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: overflow encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: invalid value encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
16:20:34 - cmdstanpy - INFO - Chain [1] start processing
16:20:35 - cmdstanpy - INFO - Chain [1] done processing
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: divide by zero encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: overflow encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: invalid value encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: divide by zero encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: overflow encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: invalid value encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: divide by zero encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: overflow encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: invalid value encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
16:20:36 - cmdstanpy - INFO - Chain [1] start processing
16:20:36 - cmdstanpy - INFO - Chain [1] done processing
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: divide by zero encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: overflow encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: invalid value encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: divide by zero encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: overflow encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: invalid value encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: divide by zero encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: overflow encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: invalid value encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
16:20:37 - cmdstanpy - INFO - Chain [1] start processing
16:20:37 - cmdstanpy - INFO - Chain [1] done processing
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: divide by zero encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: overflow encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: invalid value encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: divide by zero encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: overflow encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: invalid value encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: divide by zero encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: overflow encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: invalid value encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
16:20:38 - cmdstanpy - INFO - Chain [1] start processing
16:20:38 - cmdstanpy - INFO - Chain [1] done processing

  0%|          | 0/8 [00:00<?, ?it/s]

16:20:38 - cmdstanpy - INFO - Chain [1] start processing
16:20:39 - cmdstanpy - INFO - Chain [1] done processing
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: divide by zero encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: overflow encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: invalid value encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: divide by zero encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: overflow encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: invalid value encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: divide by zero encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: overflow encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: invalid value encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
16:20:40 - cmdstanpy - INFO - Chain [1] start processing
16:20:41 - cmdstanpy - INFO - Chain [1] done processing
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: divide by zero encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: overflow encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: invalid value encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: divide by zero encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: overflow encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: invalid value encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: divide by zero encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: overflow encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: invalid value encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
16:20:42 - cmdstanpy - INFO - Chain [1] start processing
16:20:44 - cmdstanpy - INFO - Chain [1] done processing
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: divide by zero encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: overflow encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: invalid value encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: divide by zero encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: overflow encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: invalid value encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: divide by zero encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: overflow encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: invalid value encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
16:20:45 - cmdstanpy - INFO - Chain [1] start processing
16:20:46 - cmdstanpy - INFO - Chain [1] done processing
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: divide by zero encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: overflow encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: invalid value encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: divide by zero encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: overflow encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: invalid value encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: divide by zero encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: overflow encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: invalid value encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
16:20:47 - cmdstanpy - INFO - Chain [1] start processing
16:20:49 - cmdstanpy - INFO - Chain [1] done processing
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: divide by zero encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: overflow encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: invalid value encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: divide by zero encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: overflow encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: invalid value encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: divide by zero encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: overflow encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: invalid value encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
16:20:49 - cmdstanpy - INFO - Chain [1] start processing
16:20:51 - cmdstanpy - INFO - Chain [1] done processing
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: divide by zero encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: overflow encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: invalid value encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: divide by zero encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: overflow encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: invalid value encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: divide by zero encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: overflow encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: invalid value encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
16:20:52 - cmdstanpy - INFO - Chain [1] start processing
16:20:52 - cmdstanpy - INFO - Chain [1] done processing
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: divide by zero encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: overflow encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: invalid value encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: divide by zero encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: overflow encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: invalid value encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: divide by zero encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: overflow encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: invalid value encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
16:20:53 - cmdstanpy - INFO - Chain [1] start processing
16:20:53 - cmdstanpy - INFO - Chain [1] done processing
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: divide by zero encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: overflow encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: invalid value encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: divide by zero encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: overflow encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: invalid value encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: divide by zero encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: overflow encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: invalid value encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
16:20:54 - cmdstanpy - INFO - Chain [1] start processing
16:20:54 - cmdstanpy - INFO - Chain [1] done processing

  0%|          | 0/8 [00:00<?, ?it/s]

16:20:54 - cmdstanpy - INFO - Chain [1] start processing
16:20:56 - cmdstanpy - INFO - Chain [1] done processing
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: divide by zero encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: overflow encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: invalid value encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: divide by zero encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: overflow encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: invalid value encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: divide by zero encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: overflow encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: invalid value encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
16:20:57 - cmdstanpy - INFO - Chain [1] start processing
16:20:58 - cmdstanpy - INFO - Chain [1] done processing
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: divide by zero encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: overflow encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: invalid value encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: divide by zero encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: overflow encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: invalid value encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: divide by zero encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: overflow encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: invalid value encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
16:20:59 - cmdstanpy - INFO - Chain [1] start processing
16:21:00 - cmdstanpy - INFO - Chain [1] done processing
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: divide by zero encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: overflow encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: invalid value encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: divide by zero encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: overflow encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: invalid value encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: divide by zero encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: overflow encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: invalid value encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
16:21:01 - cmdstanpy - INFO - Chain [1] start processing
16:21:02 - cmdstanpy - INFO - Chain [1] done processing
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: divide by zero encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: overflow encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: invalid value encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: divide by zero encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: overflow encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: invalid value encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: divide by zero encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: overflow encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: invalid value encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
16:21:03 - cmdstanpy - INFO - Chain [1] start processing
16:21:05 - cmdstanpy - INFO - Chain [1] done processing
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: divide by zero encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: overflow encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: invalid value encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: divide by zero encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: overflow encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: invalid value encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: divide by zero encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: overflow encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: invalid value encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
16:21:05 - cmdstanpy - INFO - Chain [1] start processing

In [ ]:

# Finetune the second model
rmses_m2 = []  # RMSEs values for the parameters for model 2

for params in all_params:
    m = Prophet(holidays=covid, **params)
    m.add_regressor('employment_count')
    m.fit(rental_and_employment)
    
    df_cv = cross_validation(m, initial='1825 days', period='180 days', horizon='365 days')
    df_p = performance_metrics(df_cv, rolling_window=1)
    rmses_m2.append(df_p['mae'].values[0])

# Find the best params
best_params_m2 = all_params[np.argmin(rmses_m2)]
print(f" Best parameters for second model: {best_params_m2}")

22:56:16 - cmdstanpy - INFO - Chain [1] start processing
22:56:16 - cmdstanpy - INFO - Chain [1] done processing

  0%|          | 0/8 [00:00<?, ?it/s]

22:56:16 - cmdstanpy - INFO - Chain [1] start processing
22:56:17 - cmdstanpy - INFO - Chain [1] done processing
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: divide by zero encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: overflow encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: invalid value encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: divide by zero encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: overflow encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: invalid value encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: divide by zero encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: overflow encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: invalid value encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
22:56:18 - cmdstanpy - INFO - Chain [1] start processing
22:56:19 - cmdstanpy - INFO - Chain [1] done processing
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: divide by zero encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: overflow encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: invalid value encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: divide by zero encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: overflow encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: invalid value encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: divide by zero encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: overflow encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: invalid value encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
22:56:20 - cmdstanpy - INFO - Chain [1] start processing
22:56:21 - cmdstanpy - INFO - Chain [1] done processing
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: divide by zero encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: overflow encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: invalid value encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: divide by zero encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: overflow encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: invalid value encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: divide by zero encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: overflow encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: invalid value encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
22:56:22 - cmdstanpy - INFO - Chain [1] start processing
22:56:23 - cmdstanpy - INFO - Chain [1] done processing
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: divide by zero encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: overflow encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: invalid value encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: divide by zero encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: overflow encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: invalid value encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: divide by zero encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: overflow encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: invalid value encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
22:56:24 - cmdstanpy - INFO - Chain [1] start processing
22:56:25 - cmdstanpy - INFO - Chain [1] done processing
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: divide by zero encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: overflow encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: invalid value encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: divide by zero encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: overflow encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: invalid value encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: divide by zero encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: overflow encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: invalid value encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
22:56:26 - cmdstanpy - INFO - Chain [1] start processing
22:56:27 - cmdstanpy - INFO - Chain [1] done processing
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: divide by zero encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: overflow encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: invalid value encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: divide by zero encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: overflow encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: invalid value encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: divide by zero encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: overflow encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: invalid value encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
22:56:28 - cmdstanpy - INFO - Chain [1] start processing
22:56:28 - cmdstanpy - INFO - Chain [1] done processing
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: divide by zero encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: overflow encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: invalid value encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: divide by zero encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: overflow encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: invalid value encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: divide by zero encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: overflow encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: invalid value encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
22:56:29 - cmdstanpy - INFO - Chain [1] start processing
22:56:29 - cmdstanpy - INFO - Chain [1] done processing
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: divide by zero encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: overflow encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: invalid value encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: divide by zero encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: overflow encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: invalid value encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: divide by zero encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: overflow encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: invalid value encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
22:56:30 - cmdstanpy - INFO - Chain [1] start processing
22:56:30 - cmdstanpy - INFO - Chain [1] done processing

  0%|          | 0/8 [00:00<?, ?it/s]

22:56:30 - cmdstanpy - INFO - Chain [1] start processing
22:56:31 - cmdstanpy - INFO - Chain [1] done processing
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: divide by zero encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: overflow encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: invalid value encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: divide by zero encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: overflow encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: invalid value encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: divide by zero encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: overflow encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: invalid value encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
22:56:32 - cmdstanpy - INFO - Chain [1] start processing
22:56:33 - cmdstanpy - INFO - Chain [1] done processing
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: divide by zero encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: overflow encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: invalid value encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: divide by zero encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: overflow encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: invalid value encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: divide by zero encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: overflow encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: invalid value encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
22:56:34 - cmdstanpy - INFO - Chain [1] start processing
22:56:35 - cmdstanpy - INFO - Chain [1] done processing
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: divide by zero encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: overflow encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: invalid value encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: divide by zero encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: overflow encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: invalid value encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: divide by zero encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: overflow encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: invalid value encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
22:56:35 - cmdstanpy - INFO - Chain [1] start processing
22:56:37 - cmdstanpy - INFO - Chain [1] done processing
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: divide by zero encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: overflow encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: invalid value encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: divide by zero encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: overflow encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: invalid value encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: divide by zero encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: overflow encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: invalid value encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
22:56:38 - cmdstanpy - INFO - Chain [1] start processing
22:56:39 - cmdstanpy - INFO - Chain [1] done processing
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: divide by zero encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: overflow encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: invalid value encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: divide by zero encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: overflow encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: invalid value encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: divide by zero encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: overflow encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: invalid value encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
22:56:40 - cmdstanpy - INFO - Chain [1] start processing
22:56:41 - cmdstanpy - INFO - Chain [1] done processing
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: divide by zero encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: overflow encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: invalid value encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: divide by zero encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: overflow encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: invalid value encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: divide by zero encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: overflow encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: invalid value encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
22:56:42 - cmdstanpy - INFO - Chain [1] start processing
22:56:42 - cmdstanpy - INFO - Chain [1] done processing
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: divide by zero encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: overflow encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: invalid value encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: divide by zero encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: overflow encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: invalid value encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: divide by zero encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: overflow encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: invalid value encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
22:56:43 - cmdstanpy - INFO - Chain [1] start processing
22:56:43 - cmdstanpy - INFO - Chain [1] done processing
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: divide by zero encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: overflow encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: invalid value encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: divide by zero encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: overflow encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: invalid value encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: divide by zero encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: overflow encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: invalid value encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
22:56:44 - cmdstanpy - INFO - Chain [1] start processing
22:56:44 - cmdstanpy - INFO - Chain [1] done processing

  0%|          | 0/8 [00:00<?, ?it/s]

22:56:44 - cmdstanpy - INFO - Chain [1] start processing
22:56:45 - cmdstanpy - INFO - Chain [1] done processing
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: divide by zero encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: overflow encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: invalid value encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: divide by zero encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: overflow encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: invalid value encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: divide by zero encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: overflow encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: invalid value encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
22:56:46 - cmdstanpy - INFO - Chain [1] start processing
22:56:47 - cmdstanpy - INFO - Chain [1] done processing
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: divide by zero encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: overflow encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: invalid value encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: divide by zero encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: overflow encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: invalid value encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: divide by zero encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: overflow encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: invalid value encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
22:56:48 - cmdstanpy - INFO - Chain [1] start processing
22:56:49 - cmdstanpy - INFO - Chain [1] done processing
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: divide by zero encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: overflow encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: invalid value encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: divide by zero encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: overflow encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: invalid value encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: divide by zero encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: overflow encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: invalid value encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
22:56:50 - cmdstanpy - INFO - Chain [1] start processing
22:56:51 - cmdstanpy - INFO - Chain [1] done processing
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: divide by zero encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: overflow encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: invalid value encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: divide by zero encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: overflow encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: invalid value encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: divide by zero encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: overflow encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: invalid value encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
22:56:52 - cmdstanpy - INFO - Chain [1] start processing
22:56:53 - cmdstanpy - INFO - Chain [1] done processing
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: divide by zero encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: overflow encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: invalid value encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: divide by zero encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: overflow encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: invalid value encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: divide by zero encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: overflow encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: invalid value encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
22:56:54 - cmdstanpy - INFO - Chain [1] start processing
22:56:55 - cmdstanpy - INFO - Chain [1] done processing
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: divide by zero encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: overflow encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: invalid value encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: divide by zero encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: overflow encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: invalid value encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: divide by zero encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: overflow encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: invalid value encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
22:56:56 - cmdstanpy - INFO - Chain [1] start processing
22:56:56 - cmdstanpy - INFO - Chain [1] done processing
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: divide by zero encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: overflow encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: invalid value encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: divide by zero encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: overflow encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: invalid value encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: divide by zero encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: overflow encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: invalid value encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
22:56:57 - cmdstanpy - INFO - Chain [1] start processing
22:56:57 - cmdstanpy - INFO - Chain [1] done processing
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: divide by zero encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: overflow encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: invalid value encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: divide by zero encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: overflow encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: invalid value encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: divide by zero encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: overflow encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: invalid value encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
22:56:58 - cmdstanpy - INFO - Chain [1] start processing
22:56:58 - cmdstanpy - INFO - Chain [1] done processing

  0%|          | 0/8 [00:00<?, ?it/s]

22:56:58 - cmdstanpy - INFO - Chain [1] start processing
22:56:59 - cmdstanpy - INFO - Chain [1] done processing
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: divide by zero encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: overflow encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: invalid value encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: divide by zero encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: overflow encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: invalid value encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: divide by zero encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: overflow encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: invalid value encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
22:57:00 - cmdstanpy - INFO - Chain [1] start processing
22:57:00 - cmdstanpy - INFO - Chain [1] done processing
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: divide by zero encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: overflow encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: invalid value encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: divide by zero encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: overflow encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: invalid value encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: divide by zero encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: overflow encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: invalid value encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
22:57:01 - cmdstanpy - INFO - Chain [1] start processing
22:57:02 - cmdstanpy - INFO - Chain [1] done processing
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: divide by zero encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: overflow encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: invalid value encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: divide by zero encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: overflow encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: invalid value encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: divide by zero encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: overflow encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: invalid value encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
22:57:03 - cmdstanpy - INFO - Chain [1] start processing
22:57:04 - cmdstanpy - INFO - Chain [1] done processing
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: divide by zero encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: overflow encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: invalid value encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: divide by zero encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: overflow encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: invalid value encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: divide by zero encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: overflow encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: invalid value encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
22:57:05 - cmdstanpy - INFO - Chain [1] start processing
22:57:06 - cmdstanpy - INFO - Chain [1] done processing
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: divide by zero encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: overflow encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: invalid value encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: divide by zero encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: overflow encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: invalid value encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: divide by zero encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: overflow encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: invalid value encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
22:57:07 - cmdstanpy - INFO - Chain [1] start processing
22:57:09 - cmdstanpy - INFO - Chain [1] done processing
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: divide by zero encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: overflow encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: invalid value encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: divide by zero encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: overflow encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: invalid value encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: divide by zero encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: overflow encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: invalid value encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
22:57:10 - cmdstanpy - INFO - Chain [1] start processing
22:57:10 - cmdstanpy - INFO - Chain [1] done processing
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: divide by zero encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: overflow encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: invalid value encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: divide by zero encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: overflow encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: invalid value encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: divide by zero encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: overflow encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: invalid value encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
22:57:10 - cmdstanpy - INFO - Chain [1] start processing
22:57:10 - cmdstanpy - INFO - Chain [1] done processing
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: divide by zero encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: overflow encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: invalid value encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: divide by zero encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: overflow encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: invalid value encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: divide by zero encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: overflow encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: invalid value encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
22:57:11 - cmdstanpy - INFO - Chain [1] start processing
22:57:11 - cmdstanpy - INFO - Chain [1] done processing

  0%|          | 0/8 [00:00<?, ?it/s]

22:57:12 - cmdstanpy - INFO - Chain [1] start processing
22:57:12 - cmdstanpy - INFO - Chain [1] done processing
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: divide by zero encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: overflow encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: invalid value encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: divide by zero encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: overflow encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: invalid value encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: divide by zero encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: overflow encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: invalid value encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
22:57:13 - cmdstanpy - INFO - Chain [1] start processing
22:57:14 - cmdstanpy - INFO - Chain [1] done processing
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: divide by zero encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: overflow encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: invalid value encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: divide by zero encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: overflow encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: invalid value encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: divide by zero encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: overflow encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: invalid value encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
22:57:15 - cmdstanpy - INFO - Chain [1] start processing
22:57:16 - cmdstanpy - INFO - Chain [1] done processing
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: divide by zero encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: overflow encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: invalid value encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: divide by zero encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: overflow encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: invalid value encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: divide by zero encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: overflow encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: invalid value encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
22:57:17 - cmdstanpy - INFO - Chain [1] start processing
22:57:18 - cmdstanpy - INFO - Chain [1] done processing
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: divide by zero encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: overflow encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: invalid value encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: divide by zero encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: overflow encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: invalid value encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: divide by zero encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: overflow encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: invalid value encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
22:57:19 - cmdstanpy - INFO - Chain [1] start processing
22:57:20 - cmdstanpy - INFO - Chain [1] done processing
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: divide by zero encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: overflow encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: invalid value encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: divide by zero encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: overflow encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: invalid value encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: divide by zero encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: overflow encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: invalid value encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
22:57:21 - cmdstanpy - INFO - Chain [1] start processing
22:57:22 - cmdstanpy - INFO - Chain [1] done processing
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: divide by zero encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: overflow encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: invalid value encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: divide by zero encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: overflow encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: invalid value encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: divide by zero encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: overflow encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: invalid value encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
22:57:23 - cmdstanpy - INFO - Chain [1] start processing
22:57:23 - cmdstanpy - INFO - Chain [1] done processing
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: divide by zero encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: overflow encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: invalid value encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: divide by zero encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: overflow encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: invalid value encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: divide by zero encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: overflow encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: invalid value encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
22:57:24 - cmdstanpy - INFO - Chain [1] start processing
22:57:24 - cmdstanpy - INFO - Chain [1] done processing
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: divide by zero encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: overflow encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: invalid value encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: divide by zero encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: overflow encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: invalid value encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: divide by zero encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: overflow encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: invalid value encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
22:57:25 - cmdstanpy - INFO - Chain [1] start processing
22:57:25 - cmdstanpy - INFO - Chain [1] done processing

  0%|          | 0/8 [00:00<?, ?it/s]

22:57:25 - cmdstanpy - INFO - Chain [1] start processing
22:57:26 - cmdstanpy - INFO - Chain [1] done processing
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: divide by zero encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: overflow encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: invalid value encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: divide by zero encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: overflow encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: invalid value encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: divide by zero encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: overflow encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: invalid value encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
22:57:27 - cmdstanpy - INFO - Chain [1] start processing
22:57:28 - cmdstanpy - INFO - Chain [1] done processing
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: divide by zero encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: overflow encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: invalid value encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: divide by zero encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: overflow encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: invalid value encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: divide by zero encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: overflow encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: invalid value encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
22:57:29 - cmdstanpy - INFO - Chain [1] start processing
22:57:30 - cmdstanpy - INFO - Chain [1] done processing
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: divide by zero encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: overflow encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: invalid value encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: divide by zero encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: overflow encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: invalid value encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: divide by zero encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: overflow encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: invalid value encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
22:57:31 - cmdstanpy - INFO - Chain [1] start processing
22:57:32 - cmdstanpy - INFO - Chain [1] done processing
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: divide by zero encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: overflow encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: invalid value encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: divide by zero encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: overflow encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: invalid value encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: divide by zero encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: overflow encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: invalid value encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
22:57:33 - cmdstanpy - INFO - Chain [1] start processing
22:57:34 - cmdstanpy - INFO - Chain [1] done processing
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: divide by zero encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: overflow encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: invalid value encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: divide by zero encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: overflow encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: invalid value encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: divide by zero encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: overflow encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: invalid value encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
22:57:35 - cmdstanpy - INFO - Chain [1] start processing
22:57:37 - cmdstanpy - INFO - Chain [1] done processing
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: divide by zero encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: overflow encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: invalid value encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: divide by zero encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: overflow encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: invalid value encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: divide by zero encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: overflow encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: invalid value encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
22:57:37 - cmdstanpy - INFO - Chain [1] start processing
22:57:37 - cmdstanpy - INFO - Chain [1] done processing
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: divide by zero encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: overflow encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: invalid value encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: divide by zero encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: overflow encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: invalid value encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: divide by zero encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: overflow encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: invalid value encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
22:57:38 - cmdstanpy - INFO - Chain [1] start processing
22:57:38 - cmdstanpy - INFO - Chain [1] done processing
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: divide by zero encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: overflow encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: invalid value encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: divide by zero encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: overflow encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: invalid value encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: divide by zero encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: overflow encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: invalid value encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
22:57:39 - cmdstanpy - INFO - Chain [1] start processing
22:57:39 - cmdstanpy - INFO - Chain [1] done processing

  0%|          | 0/8 [00:00<?, ?it/s]

22:57:40 - cmdstanpy - INFO - Chain [1] start processing
22:57:40 - cmdstanpy - INFO - Chain [1] done processing
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: divide by zero encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: overflow encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: invalid value encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: divide by zero encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: overflow encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: invalid value encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: divide by zero encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: overflow encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: invalid value encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
22:57:41 - cmdstanpy - INFO - Chain [1] start processing
22:57:42 - cmdstanpy - INFO - Chain [1] done processing
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: divide by zero encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: overflow encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: invalid value encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: divide by zero encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: overflow encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: invalid value encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: divide by zero encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: overflow encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: invalid value encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
22:57:43 - cmdstanpy - INFO - Chain [1] start processing
22:57:44 - cmdstanpy - INFO - Chain [1] done processing
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: divide by zero encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: overflow encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: invalid value encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: divide by zero encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: overflow encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: invalid value encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: divide by zero encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: overflow encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: invalid value encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
22:57:45 - cmdstanpy - INFO - Chain [1] start processing
22:57:46 - cmdstanpy - INFO - Chain [1] done processing
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: divide by zero encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: overflow encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: invalid value encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: divide by zero encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: overflow encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: invalid value encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: divide by zero encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: overflow encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: invalid value encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
22:57:47 - cmdstanpy - INFO - Chain [1] start processing
22:57:48 - cmdstanpy - INFO - Chain [1] done processing
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: divide by zero encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: overflow encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: invalid value encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: divide by zero encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: overflow encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: invalid value encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: divide by zero encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: overflow encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: invalid value encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
22:57:49 - cmdstanpy - INFO - Chain [1] start processing
22:57:50 - cmdstanpy - INFO - Chain [1] done processing
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: divide by zero encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: overflow encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: invalid value encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: divide by zero encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: overflow encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: invalid value encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: divide by zero encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: overflow encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: invalid value encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
22:57:51 - cmdstanpy - INFO - Chain [1] start processing
22:57:51 - cmdstanpy - INFO - Chain [1] done processing
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: divide by zero encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: overflow encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: invalid value encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: divide by zero encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: overflow encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: invalid value encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: divide by zero encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: overflow encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: invalid value encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
22:57:52 - cmdstanpy - INFO - Chain [1] start processing
22:57:52 - cmdstanpy - INFO - Chain [1] done processing
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: divide by zero encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: overflow encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: invalid value encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: divide by zero encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: overflow encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: invalid value encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: divide by zero encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: overflow encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: invalid value encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
22:57:53 - cmdstanpy - INFO - Chain [1] start processing
22:57:53 - cmdstanpy - INFO - Chain [1] done processing

  0%|          | 0/8 [00:00<?, ?it/s]

22:57:53 - cmdstanpy - INFO - Chain [1] start processing
22:57:54 - cmdstanpy - INFO - Chain [1] done processing
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: divide by zero encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: overflow encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: invalid value encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: divide by zero encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: overflow encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: invalid value encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: divide by zero encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: overflow encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: invalid value encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
22:57:55 - cmdstanpy - INFO - Chain [1] start processing
22:57:56 - cmdstanpy - INFO - Chain [1] done processing
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: divide by zero encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: overflow encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: invalid value encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: divide by zero encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: overflow encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: invalid value encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: divide by zero encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: overflow encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: invalid value encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
22:57:56 - cmdstanpy - INFO - Chain [1] start processing
22:57:57 - cmdstanpy - INFO - Chain [1] done processing
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: divide by zero encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: overflow encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: invalid value encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: divide by zero encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: overflow encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: invalid value encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: divide by zero encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: overflow encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: invalid value encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
22:57:58 - cmdstanpy - INFO - Chain [1] start processing
22:57:59 - cmdstanpy - INFO - Chain [1] done processing
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: divide by zero encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: overflow encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: invalid value encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: divide by zero encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: overflow encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: invalid value encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: divide by zero encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: overflow encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: invalid value encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
22:58:00 - cmdstanpy - INFO - Chain [1] start processing
22:58:01 - cmdstanpy - INFO - Chain [1] done processing
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: divide by zero encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: overflow encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: invalid value encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: divide by zero encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: overflow encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: invalid value encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: divide by zero encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: overflow encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: invalid value encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
22:58:02 - cmdstanpy - INFO - Chain [1] start processing
22:58:03 - cmdstanpy - INFO - Chain [1] done processing
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: divide by zero encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: overflow encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: invalid value encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: divide by zero encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: overflow encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: invalid value encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: divide by zero encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: overflow encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: invalid value encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
22:58:04 - cmdstanpy - INFO - Chain [1] start processing
22:58:04 - cmdstanpy - INFO - Chain [1] done processing
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: divide by zero encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: overflow encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: invalid value encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: divide by zero encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: overflow encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: invalid value encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: divide by zero encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: overflow encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: invalid value encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
22:58:05 - cmdstanpy - INFO - Chain [1] start processing
22:58:05 - cmdstanpy - INFO - Chain [1] done processing
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: divide by zero encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: overflow encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: invalid value encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: divide by zero encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: overflow encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: invalid value encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: divide by zero encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: overflow encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: invalid value encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
22:58:06 - cmdstanpy - INFO - Chain [1] start processing
22:58:06 - cmdstanpy - INFO - Chain [1] done processing

  0%|          | 0/8 [00:00<?, ?it/s]

22:58:07 - cmdstanpy - INFO - Chain [1] start processing
22:58:07 - cmdstanpy - INFO - Chain [1] done processing
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: divide by zero encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: overflow encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: invalid value encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: divide by zero encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: overflow encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: invalid value encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: divide by zero encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: overflow encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: invalid value encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
22:58:08 - cmdstanpy - INFO - Chain [1] start processing
22:58:09 - cmdstanpy - INFO - Chain [1] done processing
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: divide by zero encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: overflow encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: invalid value encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: divide by zero encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: overflow encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: invalid value encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: divide by zero encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: overflow encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: invalid value encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
22:58:10 - cmdstanpy - INFO - Chain [1] start processing
22:58:11 - cmdstanpy - INFO - Chain [1] done processing
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: divide by zero encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: overflow encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: invalid value encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: divide by zero encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: overflow encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: invalid value encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: divide by zero encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: overflow encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: invalid value encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
22:58:11 - cmdstanpy - INFO - Chain [1] start processing
22:58:13 - cmdstanpy - INFO - Chain [1] done processing
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: divide by zero encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: overflow encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: invalid value encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: divide by zero encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: overflow encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: invalid value encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: divide by zero encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: overflow encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: invalid value encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
22:58:13 - cmdstanpy - INFO - Chain [1] start processing
22:58:15 - cmdstanpy - INFO - Chain [1] done processing
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: divide by zero encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: overflow encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: invalid value encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: divide by zero encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: overflow encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: invalid value encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: divide by zero encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: overflow encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: invalid value encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
22:58:16 - cmdstanpy - INFO - Chain [1] start processing
22:58:17 - cmdstanpy - INFO - Chain [1] done processing
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: divide by zero encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: overflow encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: invalid value encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: divide by zero encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: overflow encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: invalid value encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: divide by zero encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: overflow encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: invalid value encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
22:58:18 - cmdstanpy - INFO - Chain [1] start processing
22:58:18 - cmdstanpy - INFO - Chain [1] done processing
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: divide by zero encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: overflow encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: invalid value encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: divide by zero encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: overflow encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: invalid value encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: divide by zero encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: overflow encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: invalid value encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
22:58:19 - cmdstanpy - INFO - Chain [1] start processing
22:58:19 - cmdstanpy - INFO - Chain [1] done processing
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: divide by zero encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: overflow encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: invalid value encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: divide by zero encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: overflow encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: invalid value encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: divide by zero encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: overflow encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: invalid value encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
22:58:20 - cmdstanpy - INFO - Chain [1] start processing
22:58:20 - cmdstanpy - INFO - Chain [1] done processing

  0%|          | 0/8 [00:00<?, ?it/s]

22:58:20 - cmdstanpy - INFO - Chain [1] start processing
22:58:21 - cmdstanpy - INFO - Chain [1] done processing
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: divide by zero encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: overflow encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: invalid value encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: divide by zero encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: overflow encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: invalid value encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: divide by zero encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: overflow encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: invalid value encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
22:58:22 - cmdstanpy - INFO - Chain [1] start processing
22:58:23 - cmdstanpy - INFO - Chain [1] done processing
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: divide by zero encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: overflow encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: invalid value encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: divide by zero encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: overflow encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: invalid value encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: divide by zero encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: overflow encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: invalid value encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
22:58:24 - cmdstanpy - INFO - Chain [1] start processing
22:58:25 - cmdstanpy - INFO - Chain [1] done processing
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: divide by zero encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: overflow encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: invalid value encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: divide by zero encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: overflow encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: invalid value encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: divide by zero encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: overflow encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: invalid value encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
22:58:26 - cmdstanpy - INFO - Chain [1] start processing
22:58:28 - cmdstanpy - INFO - Chain [1] done processing
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: divide by zero encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: overflow encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: invalid value encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: divide by zero encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: overflow encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: invalid value encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: divide by zero encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: overflow encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: invalid value encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
22:58:29 - cmdstanpy - INFO - Chain [1] start processing
22:58:31 - cmdstanpy - INFO - Chain [1] done processing
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: divide by zero encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: overflow encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: invalid value encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: divide by zero encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: overflow encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: invalid value encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: divide by zero encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: overflow encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: invalid value encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
22:58:32 - cmdstanpy - INFO - Chain [1] start processing
22:58:34 - cmdstanpy - INFO - Chain [1] done processing
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: divide by zero encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: overflow encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: invalid value encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: divide by zero encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: overflow encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: invalid value encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: divide by zero encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: overflow encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: invalid value encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
22:58:35 - cmdstanpy - INFO - Chain [1] start processing
22:58:35 - cmdstanpy - INFO - Chain [1] done processing
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: divide by zero encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: overflow encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: invalid value encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: divide by zero encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: overflow encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: invalid value encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: divide by zero encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: overflow encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: invalid value encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
22:58:36 - cmdstanpy - INFO - Chain [1] start processing
22:58:36 - cmdstanpy - INFO - Chain [1] done processing
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: divide by zero encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: overflow encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: invalid value encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: divide by zero encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: overflow encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: invalid value encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: divide by zero encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: overflow encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: invalid value encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
22:58:37 - cmdstanpy - INFO - Chain [1] start processing
22:58:37 - cmdstanpy - INFO - Chain [1] done processing

  0%|          | 0/8 [00:00<?, ?it/s]

22:58:37 - cmdstanpy - INFO - Chain [1] start processing
22:58:38 - cmdstanpy - INFO - Chain [1] done processing
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: divide by zero encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: overflow encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: invalid value encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: divide by zero encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: overflow encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: invalid value encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: divide by zero encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: overflow encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: invalid value encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
22:58:39 - cmdstanpy - INFO - Chain [1] start processing
22:58:40 - cmdstanpy - INFO - Chain [1] done processing
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: divide by zero encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: overflow encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: invalid value encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: divide by zero encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: overflow encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: invalid value encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: divide by zero encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: overflow encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: invalid value encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
22:58:41 - cmdstanpy - INFO - Chain [1] start processing
22:58:42 - cmdstanpy - INFO - Chain [1] done processing
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: divide by zero encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: overflow encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: invalid value encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: divide by zero encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: overflow encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: invalid value encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: divide by zero encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: overflow encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: invalid value encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
22:58:43 - cmdstanpy - INFO - Chain [1] start processing
22:58:45 - cmdstanpy - INFO - Chain [1] done processing
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: divide by zero encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: overflow encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: invalid value encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: divide by zero encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: overflow encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: invalid value encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: divide by zero encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: overflow encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: invalid value encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
22:58:46 - cmdstanpy - INFO - Chain [1] start processing
22:58:47 - cmdstanpy - INFO - Chain [1] done processing
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: divide by zero encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: overflow encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: invalid value encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: divide by zero encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: overflow encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: invalid value encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: divide by zero encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: overflow encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: invalid value encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
22:58:48 - cmdstanpy - INFO - Chain [1] start processing
22:58:50 - cmdstanpy - INFO - Chain [1] done processing
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: divide by zero encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: overflow encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: invalid value encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: divide by zero encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: overflow encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: invalid value encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: divide by zero encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: overflow encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: invalid value encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
22:58:51 - cmdstanpy - INFO - Chain [1] start processing
22:58:51 - cmdstanpy - INFO - Chain [1] done processing
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: divide by zero encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: overflow encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: invalid value encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: divide by zero encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: overflow encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: invalid value encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: divide by zero encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: overflow encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: invalid value encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
22:58:51 - cmdstanpy - INFO - Chain [1] start processing
22:58:52 - cmdstanpy - INFO - Chain [1] done processing
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: divide by zero encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: overflow encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: invalid value encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: divide by zero encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: overflow encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: invalid value encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: divide by zero encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: overflow encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: invalid value encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
22:58:52 - cmdstanpy - INFO - Chain [1] start processing
22:58:52 - cmdstanpy - INFO - Chain [1] done processing

  0%|          | 0/8 [00:00<?, ?it/s]

22:58:53 - cmdstanpy - INFO - Chain [1] start processing
22:58:54 - cmdstanpy - INFO - Chain [1] done processing
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: divide by zero encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: overflow encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: invalid value encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: divide by zero encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: overflow encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: invalid value encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: divide by zero encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: overflow encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: invalid value encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
22:58:55 - cmdstanpy - INFO - Chain [1] start processing
22:58:56 - cmdstanpy - INFO - Chain [1] done processing
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: divide by zero encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: overflow encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: invalid value encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: divide by zero encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: overflow encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: invalid value encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: divide by zero encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: overflow encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: invalid value encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
22:58:57 - cmdstanpy - INFO - Chain [1] start processing
22:58:58 - cmdstanpy - INFO - Chain [1] done processing
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: divide by zero encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: overflow encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: invalid value encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: divide by zero encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: overflow encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: invalid value encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: divide by zero encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: overflow encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: invalid value encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
22:58:59 - cmdstanpy - INFO - Chain [1] start processing
22:59:01 - cmdstanpy - INFO - Chain [1] done processing
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: divide by zero encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: overflow encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: invalid value encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: divide by zero encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: overflow encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: invalid value encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: divide by zero encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: overflow encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: invalid value encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
22:59:02 - cmdstanpy - INFO - Chain [1] start processing
22:59:04 - cmdstanpy - INFO - Chain [1] done processing
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: divide by zero encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: overflow encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: invalid value encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: divide by zero encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: overflow encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: invalid value encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: divide by zero encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: overflow encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: invalid value encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
22:59:05 - cmdstanpy - INFO - Chain [1] start processing
22:59:06 - cmdstanpy - INFO - Chain [1] done processing
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: divide by zero encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: overflow encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: invalid value encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: divide by zero encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: overflow encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: invalid value encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: divide by zero encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: overflow encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: invalid value encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
22:59:07 - cmdstanpy - INFO - Chain [1] start processing
22:59:07 - cmdstanpy - INFO - Chain [1] done processing
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: divide by zero encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: overflow encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: invalid value encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: divide by zero encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: overflow encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: invalid value encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: divide by zero encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: overflow encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: invalid value encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
22:59:08 - cmdstanpy - INFO - Chain [1] start processing
22:59:08 - cmdstanpy - INFO - Chain [1] done processing
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: divide by zero encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: overflow encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: invalid value encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: divide by zero encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: overflow encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: invalid value encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: divide by zero encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: overflow encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: invalid value encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
22:59:09 - cmdstanpy - INFO - Chain [1] start processing
22:59:09 - cmdstanpy - INFO - Chain [1] done processing

  0%|          | 0/8 [00:00<?, ?it/s]

22:59:10 - cmdstanpy - INFO - Chain [1] start processing
22:59:11 - cmdstanpy - INFO - Chain [1] done processing
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: divide by zero encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: overflow encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: invalid value encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: divide by zero encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: overflow encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: invalid value encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: divide by zero encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: overflow encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: invalid value encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
22:59:11 - cmdstanpy - INFO - Chain [1] start processing
22:59:13 - cmdstanpy - INFO - Chain [1] done processing
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: divide by zero encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: overflow encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: invalid value encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: divide by zero encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: overflow encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: invalid value encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: divide by zero encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: overflow encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: invalid value encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
22:59:14 - cmdstanpy - INFO - Chain [1] start processing
22:59:15 - cmdstanpy - INFO - Chain [1] done processing
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: divide by zero encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: overflow encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: invalid value encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: divide by zero encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: overflow encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: invalid value encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: divide by zero encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: overflow encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: invalid value encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
22:59:16 - cmdstanpy - INFO - Chain [1] start processing
22:59:17 - cmdstanpy - INFO - Chain [1] done processing
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: divide by zero encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: overflow encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: invalid value encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: divide by zero encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: overflow encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: invalid value encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: divide by zero encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: overflow encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: invalid value encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
22:59:18 - cmdstanpy - INFO - Chain [1] start processing
22:59:19 - cmdstanpy - INFO - Chain [1] done processing
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: divide by zero encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: overflow encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: invalid value encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: divide by zero encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: overflow encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: invalid value encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: divide by zero encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: overflow encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: invalid value encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
22:59:20 - cmdstanpy - INFO - Chain [1] start processing
22:59:22 - cmdstanpy - INFO - Chain [1] done processing
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: divide by zero encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: overflow encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: invalid value encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: divide by zero encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: overflow encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: invalid value encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: divide by zero encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: overflow encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: invalid value encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
22:59:23 - cmdstanpy - INFO - Chain [1] start processing
22:59:23 - cmdstanpy - INFO - Chain [1] done processing
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: divide by zero encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: overflow encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: invalid value encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: divide by zero encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: overflow encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: invalid value encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: divide by zero encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: overflow encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: invalid value encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
22:59:24 - cmdstanpy - INFO - Chain [1] start processing
22:59:24 - cmdstanpy - INFO - Chain [1] done processing
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: divide by zero encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: overflow encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: invalid value encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: divide by zero encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: overflow encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: invalid value encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: divide by zero encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: overflow encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: invalid value encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
22:59:25 - cmdstanpy - INFO - Chain [1] start processing
22:59:25 - cmdstanpy - INFO - Chain [1] done processing

  0%|          | 0/8 [00:00<?, ?it/s]

22:59:25 - cmdstanpy - INFO - Chain [1] start processing
22:59:26 - cmdstanpy - INFO - Chain [1] done processing
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: divide by zero encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: overflow encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: invalid value encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: divide by zero encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: overflow encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: invalid value encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: divide by zero encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: overflow encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: invalid value encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
22:59:27 - cmdstanpy - INFO - Chain [1] start processing
22:59:28 - cmdstanpy - INFO - Chain [1] done processing
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: divide by zero encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: overflow encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: invalid value encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: divide by zero encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: overflow encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: invalid value encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: divide by zero encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: overflow encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: invalid value encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
22:59:29 - cmdstanpy - INFO - Chain [1] start processing
22:59:30 - cmdstanpy - INFO - Chain [1] done processing
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: divide by zero encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: overflow encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: invalid value encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: divide by zero encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: overflow encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: invalid value encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: divide by zero encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: overflow encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: invalid value encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
22:59:31 - cmdstanpy - INFO - Chain [1] start processing
22:59:32 - cmdstanpy - INFO - Chain [1] done processing
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: divide by zero encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: overflow encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: invalid value encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: divide by zero encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: overflow encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: invalid value encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: divide by zero encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: overflow encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: invalid value encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
22:59:33 - cmdstanpy - INFO - Chain [1] start processing
22:59:35 - cmdstanpy - INFO - Chain [1] done processing
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: divide by zero encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: overflow encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: invalid value encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: divide by zero encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: overflow encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: invalid value encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: divide by zero encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: overflow encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: invalid value encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
22:59:36 - cmdstanpy - INFO - Chain [1] start processing
22:59:38 - cmdstanpy - INFO - Chain [1] done processing
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: divide by zero encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: overflow encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: invalid value encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: divide by zero encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: overflow encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: invalid value encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: divide by zero encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: overflow encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: invalid value encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
22:59:39 - cmdstanpy - INFO - Chain [1] start processing
22:59:39 - cmdstanpy - INFO - Chain [1] done processing
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: divide by zero encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: overflow encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: invalid value encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: divide by zero encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: overflow encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: invalid value encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: divide by zero encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: overflow encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: invalid value encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
22:59:40 - cmdstanpy - INFO - Chain [1] start processing
22:59:40 - cmdstanpy - INFO - Chain [1] done processing
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: divide by zero encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: overflow encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: invalid value encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: divide by zero encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: overflow encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: invalid value encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: divide by zero encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: overflow encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: invalid value encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
22:59:41 - cmdstanpy - INFO - Chain [1] start processing
22:59:41 - cmdstanpy - INFO - Chain [1] done processing

  0%|          | 0/8 [00:00<?, ?it/s]

22:59:41 - cmdstanpy - INFO - Chain [1] start processing
22:59:42 - cmdstanpy - INFO - Chain [1] done processing
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: divide by zero encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: overflow encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: invalid value encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: divide by zero encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: overflow encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: invalid value encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: divide by zero encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: overflow encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: invalid value encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
22:59:43 - cmdstanpy - INFO - Chain [1] start processing
22:59:44 - cmdstanpy - INFO - Chain [1] done processing
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: divide by zero encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: overflow encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: invalid value encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: divide by zero encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: overflow encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: invalid value encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: divide by zero encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: overflow encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: invalid value encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
22:59:45 - cmdstanpy - INFO - Chain [1] start processing
22:59:46 - cmdstanpy - INFO - Chain [1] done processing
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: divide by zero encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: overflow encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: invalid value encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: divide by zero encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: overflow encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: invalid value encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: divide by zero encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: overflow encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: invalid value encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
22:59:47 - cmdstanpy - INFO - Chain [1] start processing
22:59:48 - cmdstanpy - INFO - Chain [1] done processing
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: divide by zero encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: overflow encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: invalid value encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: divide by zero encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: overflow encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: invalid value encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: divide by zero encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: overflow encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: invalid value encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
22:59:49 - cmdstanpy - INFO - Chain [1] start processing
22:59:51 - cmdstanpy - INFO - Chain [1] done processing
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: divide by zero encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: overflow encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: invalid value encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: divide by zero encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: overflow encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: invalid value encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: divide by zero encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: overflow encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: invalid value encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
22:59:52 - cmdstanpy - INFO - Chain [1] start processing
22:59:54 - cmdstanpy - INFO - Chain [1] done processing
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: divide by zero encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: overflow encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: invalid value encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: divide by zero encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: overflow encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: invalid value encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: divide by zero encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: overflow encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: invalid value encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
22:59:55 - cmdstanpy - INFO - Chain [1] start processing
22:59:55 - cmdstanpy - INFO - Chain [1] done processing
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: divide by zero encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: overflow encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: invalid value encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: divide by zero encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: overflow encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: invalid value encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: divide by zero encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: overflow encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: invalid value encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
22:59:55 - cmdstanpy - INFO - Chain [1] start processing
22:59:55 - cmdstanpy - INFO - Chain [1] done processing
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: divide by zero encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: overflow encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: invalid value encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: divide by zero encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: overflow encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: invalid value encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: divide by zero encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: overflow encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: invalid value encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
22:59:56 - cmdstanpy - INFO - Chain [1] start processing
22:59:56 - cmdstanpy - INFO - Chain [1] done processing

  0%|          | 0/8 [00:00<?, ?it/s]

22:59:57 - cmdstanpy - INFO - Chain [1] start processing
22:59:58 - cmdstanpy - INFO - Chain [1] done processing
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: divide by zero encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: overflow encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: invalid value encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: divide by zero encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: overflow encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: invalid value encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: divide by zero encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: overflow encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: invalid value encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
22:59:59 - cmdstanpy - INFO - Chain [1] start processing
22:59:59 - cmdstanpy - INFO - Chain [1] done processing
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: divide by zero encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: overflow encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: invalid value encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: divide by zero encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: overflow encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: invalid value encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: divide by zero encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: overflow encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: invalid value encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
23:00:00 - cmdstanpy - INFO - Chain [1] start processing
23:00:01 - cmdstanpy - INFO - Chain [1] done processing
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: divide by zero encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: overflow encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: invalid value encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: divide by zero encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: overflow encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: invalid value encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: divide by zero encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: overflow encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: invalid value encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
23:00:02 - cmdstanpy - INFO - Chain [1] start processing
23:00:04 - cmdstanpy - INFO - Chain [1] done processing
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: divide by zero encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: overflow encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: invalid value encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: divide by zero encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: overflow encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: invalid value encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: divide by zero encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: overflow encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: invalid value encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
23:00:05 - cmdstanpy - INFO - Chain [1] start processing
23:00:07 - cmdstanpy - INFO - Chain [1] done processing
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: divide by zero encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: overflow encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: invalid value encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: divide by zero encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: overflow encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: invalid value encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: divide by zero encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: overflow encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: invalid value encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
23:00:08 - cmdstanpy - INFO - Chain [1] start processing
23:00:09 - cmdstanpy - INFO - Chain [1] done processing
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: divide by zero encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: overflow encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: invalid value encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: divide by zero encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: overflow encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: invalid value encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: divide by zero encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: overflow encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: invalid value encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
23:00:10 - cmdstanpy - INFO - Chain [1] start processing
23:00:10 - cmdstanpy - INFO - Chain [1] done processing
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: divide by zero encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: overflow encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: invalid value encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: divide by zero encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: overflow encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: invalid value encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: divide by zero encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: overflow encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: invalid value encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
23:00:11 - cmdstanpy - INFO - Chain [1] start processing
23:00:11 - cmdstanpy - INFO - Chain [1] done processing
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: divide by zero encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: overflow encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: invalid value encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: divide by zero encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: overflow encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: invalid value encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: divide by zero encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: overflow encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: invalid value encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
23:00:12 - cmdstanpy - INFO - Chain [1] start processing
23:00:12 - cmdstanpy - INFO - Chain [1] done processing

  0%|          | 0/8 [00:00<?, ?it/s]

23:00:12 - cmdstanpy - INFO - Chain [1] start processing
23:00:13 - cmdstanpy - INFO - Chain [1] done processing
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: divide by zero encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: overflow encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: invalid value encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: divide by zero encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: overflow encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: invalid value encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: divide by zero encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: overflow encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: invalid value encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
23:00:14 - cmdstanpy - INFO - Chain [1] start processing
23:00:16 - cmdstanpy - INFO - Chain [1] done processing
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: divide by zero encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: overflow encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: invalid value encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: divide by zero encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: overflow encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: invalid value encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: divide by zero encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: overflow encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: invalid value encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
23:00:16 - cmdstanpy - INFO - Chain [1] start processing
23:00:17 - cmdstanpy - INFO - Chain [1] done processing
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: divide by zero encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: overflow encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: invalid value encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: divide by zero encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: overflow encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: invalid value encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: divide by zero encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: overflow encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: invalid value encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
23:00:18 - cmdstanpy - INFO - Chain [1] start processing
23:00:20 - cmdstanpy - INFO - Chain [1] done processing
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: divide by zero encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: overflow encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: invalid value encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: divide by zero encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: overflow encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: invalid value encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: divide by zero encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: overflow encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: invalid value encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
23:00:21 - cmdstanpy - INFO - Chain [1] start processing
23:00:23 - cmdstanpy - INFO - Chain [1] done processing
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: divide by zero encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: overflow encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: invalid value encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: divide by zero encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: overflow encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: invalid value encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: divide by zero encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: overflow encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: invalid value encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
23:00:23 - cmdstanpy - INFO - Chain [1] start processing
23:00:25 - cmdstanpy - INFO - Chain [1] done processing
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: divide by zero encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: overflow encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: invalid value encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: divide by zero encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: overflow encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: invalid value encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: divide by zero encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: overflow encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: invalid value encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
23:00:26 - cmdstanpy - INFO - Chain [1] start processing
23:00:26 - cmdstanpy - INFO - Chain [1] done processing
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: divide by zero encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: overflow encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: invalid value encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: divide by zero encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: overflow encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: invalid value encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: divide by zero encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: overflow encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: invalid value encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
23:00:27 - cmdstanpy - INFO - Chain [1] start processing
23:00:27 - cmdstanpy - INFO - Chain [1] done processing
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: divide by zero encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: overflow encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: invalid value encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: divide by zero encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: overflow encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: invalid value encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: divide by zero encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: overflow encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: invalid value encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
23:00:28 - cmdstanpy - INFO - Chain [1] start processing
23:00:28 - cmdstanpy - INFO - Chain [1] done processing

  0%|          | 0/8 [00:00<?, ?it/s]

23:00:28 - cmdstanpy - INFO - Chain [1] start processing
23:00:29 - cmdstanpy - INFO - Chain [1] done processing
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: divide by zero encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: overflow encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: invalid value encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: divide by zero encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: overflow encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: invalid value encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: divide by zero encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: overflow encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: invalid value encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
23:00:30 - cmdstanpy - INFO - Chain [1] start processing
23:00:31 - cmdstanpy - INFO - Chain [1] done processing
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: divide by zero encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: overflow encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: invalid value encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: divide by zero encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: overflow encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: invalid value encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: divide by zero encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: overflow encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: invalid value encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
23:00:32 - cmdstanpy - INFO - Chain [1] start processing
23:00:33 - cmdstanpy - INFO - Chain [1] done processing
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: divide by zero encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: overflow encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: invalid value encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: divide by zero encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: overflow encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: invalid value encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: divide by zero encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: overflow encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: invalid value encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
23:00:34 - cmdstanpy - INFO - Chain [1] start processing
23:00:35 - cmdstanpy - INFO - Chain [1] done processing
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: divide by zero encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: overflow encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: invalid value encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: divide by zero encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: overflow encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: invalid value encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: divide by zero encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: overflow encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: invalid value encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
23:00:36 - cmdstanpy - INFO - Chain [1] start processing
23:00:38 - cmdstanpy - INFO - Chain [1] done processing
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: divide by zero encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: overflow encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: invalid value encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: divide by zero encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: overflow encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: invalid value encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: divide by zero encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: overflow encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: invalid value encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
23:00:39 - cmdstanpy - INFO - Chain [1] start processing
23:00:40 - cmdstanpy - INFO - Chain [1] done processing
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: divide by zero encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: overflow encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: invalid value encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: divide by zero encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: overflow encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: invalid value encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: divide by zero encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: overflow encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: invalid value encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
23:00:41 - cmdstanpy - INFO - Chain [1] start processing
23:00:41 - cmdstanpy - INFO - Chain [1] done processing
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: divide by zero encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: overflow encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: invalid value encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: divide by zero encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: overflow encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: invalid value encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: divide by zero encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: overflow encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: invalid value encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
23:00:42 - cmdstanpy - INFO - Chain [1] start processing
23:00:42 - cmdstanpy - INFO - Chain [1] done processing
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: divide by zero encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: overflow encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: invalid value encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: divide by zero encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: overflow encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: invalid value encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: divide by zero encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: overflow encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: invalid value encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
23:00:43 - cmdstanpy - INFO - Chain [1] start processing
23:00:43 - cmdstanpy - INFO - Chain [1] done processing

  0%|          | 0/8 [00:00<?, ?it/s]

23:00:43 - cmdstanpy - INFO - Chain [1] start processing
23:00:45 - cmdstanpy - INFO - Chain [1] done processing
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: divide by zero encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: overflow encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: invalid value encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: divide by zero encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: overflow encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: invalid value encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: divide by zero encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: overflow encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: invalid value encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
23:00:46 - cmdstanpy - INFO - Chain [1] start processing
23:00:47 - cmdstanpy - INFO - Chain [1] done processing
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: divide by zero encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: overflow encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: invalid value encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: divide by zero encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: overflow encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: invalid value encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: divide by zero encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: overflow encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: invalid value encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
23:00:48 - cmdstanpy - INFO - Chain [1] start processing
23:00:49 - cmdstanpy - INFO - Chain [1] done processing
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: divide by zero encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: overflow encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: invalid value encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: divide by zero encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: overflow encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: invalid value encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: divide by zero encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: overflow encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: invalid value encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
23:00:50 - cmdstanpy - INFO - Chain [1] start processing
23:00:52 - cmdstanpy - INFO - Chain [1] done processing
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: divide by zero encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: overflow encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: invalid value encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: divide by zero encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: overflow encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: invalid value encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: divide by zero encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: overflow encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: invalid value encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
23:00:53 - cmdstanpy - INFO - Chain [1] start processing
23:00:54 - cmdstanpy - INFO - Chain [1] done processing
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: divide by zero encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: overflow encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: invalid value encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: divide by zero encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: overflow encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: invalid value encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: divide by zero encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: overflow encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: invalid value encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
23:00:55 - cmdstanpy - INFO - Chain [1] start processing
23:00:56 - cmdstanpy - INFO - Chain [1] done processing
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: divide by zero encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: overflow encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: invalid value encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: divide by zero encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: overflow encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: invalid value encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: divide by zero encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: overflow encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: invalid value encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
23:00:57 - cmdstanpy - INFO - Chain [1] start processing
23:00:57 - cmdstanpy - INFO - Chain [1] done processing
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: divide by zero encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: overflow encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: invalid value encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: divide by zero encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: overflow encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: invalid value encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: divide by zero encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: overflow encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: invalid value encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
23:00:58 - cmdstanpy - INFO - Chain [1] start processing
23:00:58 - cmdstanpy - INFO - Chain [1] done processing
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: divide by zero encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: overflow encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: invalid value encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: divide by zero encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: overflow encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: invalid value encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: divide by zero encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: overflow encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: invalid value encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
23:00:59 - cmdstanpy - INFO - Chain [1] start processing
23:00:59 - cmdstanpy - INFO - Chain [1] done processing

  0%|          | 0/8 [00:00<?, ?it/s]

23:00:59 - cmdstanpy - INFO - Chain [1] start processing
23:01:01 - cmdstanpy - INFO - Chain [1] done processing
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: divide by zero encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: overflow encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: invalid value encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: divide by zero encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: overflow encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: invalid value encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: divide by zero encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: overflow encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: invalid value encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
23:01:02 - cmdstanpy - INFO - Chain [1] start processing
23:01:03 - cmdstanpy - INFO - Chain [1] done processing
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: divide by zero encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: overflow encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: invalid value encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: divide by zero encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: overflow encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: invalid value encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: divide by zero encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: overflow encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: invalid value encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
23:01:04 - cmdstanpy - INFO - Chain [1] start processing
23:01:05 - cmdstanpy - INFO - Chain [1] done processing
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: divide by zero encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: overflow encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: invalid value encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: divide by zero encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: overflow encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: invalid value encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: divide by zero encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: overflow encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: invalid value encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
23:01:06 - cmdstanpy - INFO - Chain [1] start processing
23:01:07 - cmdstanpy - INFO - Chain [1] done processing
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: divide by zero encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: overflow encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: invalid value encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: divide by zero encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: overflow encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: invalid value encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: divide by zero encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: overflow encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: invalid value encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
23:01:08 - cmdstanpy - INFO - Chain [1] start processing
23:01:10 - cmdstanpy - INFO - Chain [1] done processing
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: divide by zero encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: overflow encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: invalid value encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: divide by zero encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: overflow encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: invalid value encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: divide by zero encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: overflow encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: invalid value encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
23:01:10 - cmdstanpy - INFO - Chain [1] start processing
23:01:11 - cmdstanpy - INFO - Chain [1] done processing
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: divide by zero encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: overflow encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: invalid value encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: divide by zero encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: overflow encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: invalid value encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: divide by zero encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: overflow encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: invalid value encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
23:01:12 - cmdstanpy - INFO - Chain [1] start processing
23:01:12 - cmdstanpy - INFO - Chain [1] done processing
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: divide by zero encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: overflow encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: invalid value encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: divide by zero encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: overflow encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: invalid value encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: divide by zero encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: overflow encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: invalid value encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
23:01:13 - cmdstanpy - INFO - Chain [1] start processing
23:01:13 - cmdstanpy - INFO - Chain [1] done processing
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: divide by zero encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: overflow encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: invalid value encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: divide by zero encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: overflow encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: invalid value encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: divide by zero encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: overflow encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: invalid value encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
23:01:14 - cmdstanpy - INFO - Chain [1] start processing
23:01:14 - cmdstanpy - INFO - Chain [1] done processing

  0%|          | 0/8 [00:00<?, ?it/s]

23:01:15 - cmdstanpy - INFO - Chain [1] start processing
23:01:16 - cmdstanpy - INFO - Chain [1] done processing
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: divide by zero encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: overflow encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: invalid value encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: divide by zero encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: overflow encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: invalid value encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: divide by zero encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: overflow encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: invalid value encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
23:01:17 - cmdstanpy - INFO - Chain [1] start processing
23:01:18 - cmdstanpy - INFO - Chain [1] done processing
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: divide by zero encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: overflow encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: invalid value encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: divide by zero encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: overflow encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: invalid value encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: divide by zero encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: overflow encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: invalid value encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
23:01:18 - cmdstanpy - INFO - Chain [1] start processing
23:01:20 - cmdstanpy - INFO - Chain [1] done processing
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: divide by zero encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: overflow encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: invalid value encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: divide by zero encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: overflow encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: invalid value encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: divide by zero encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: overflow encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: invalid value encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
23:01:21 - cmdstanpy - INFO - Chain [1] start processing
23:01:22 - cmdstanpy - INFO - Chain [1] done processing
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: divide by zero encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: overflow encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: invalid value encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: divide by zero encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: overflow encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: invalid value encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: divide by zero encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: overflow encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: invalid value encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
23:01:23 - cmdstanpy - INFO - Chain [1] start processing
23:01:24 - cmdstanpy - INFO - Chain [1] done processing
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: divide by zero encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: overflow encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: invalid value encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: divide by zero encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: overflow encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: invalid value encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: divide by zero encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: overflow encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: invalid value encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
23:01:25 - cmdstanpy - INFO - Chain [1] start processing
23:01:27 - cmdstanpy - INFO - Chain [1] done processing
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: divide by zero encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: overflow encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: invalid value encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: divide by zero encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: overflow encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: invalid value encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: divide by zero encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: overflow encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: invalid value encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
23:01:28 - cmdstanpy - INFO - Chain [1] start processing
23:01:28 - cmdstanpy - INFO - Chain [1] done processing
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: divide by zero encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: overflow encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: invalid value encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: divide by zero encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: overflow encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: invalid value encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: divide by zero encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: overflow encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: invalid value encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
23:01:28 - cmdstanpy - INFO - Chain [1] start processing
23:01:28 - cmdstanpy - INFO - Chain [1] done processing
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: divide by zero encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: overflow encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: invalid value encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: divide by zero encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: overflow encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: invalid value encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: divide by zero encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: overflow encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: invalid value encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
23:01:29 - cmdstanpy - INFO - Chain [1] start processing
23:01:29 - cmdstanpy - INFO - Chain [1] done processing

  0%|          | 0/8 [00:00<?, ?it/s]

23:01:30 - cmdstanpy - INFO - Chain [1] start processing
23:01:31 - cmdstanpy - INFO - Chain [1] done processing
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: divide by zero encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: overflow encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: invalid value encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: divide by zero encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: overflow encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: invalid value encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: divide by zero encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: overflow encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: invalid value encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
23:01:32 - cmdstanpy - INFO - Chain [1] start processing
23:01:33 - cmdstanpy - INFO - Chain [1] done processing
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: divide by zero encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: overflow encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: invalid value encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: divide by zero encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: overflow encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: invalid value encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: divide by zero encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: overflow encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: invalid value encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
23:01:34 - cmdstanpy - INFO - Chain [1] start processing
23:01:36 - cmdstanpy - INFO - Chain [1] done processing
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: divide by zero encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: overflow encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: invalid value encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: divide by zero encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: overflow encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: invalid value encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: divide by zero encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: overflow encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: invalid value encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
23:01:36 - cmdstanpy - INFO - Chain [1] start processing
23:01:38 - cmdstanpy - INFO - Chain [1] done processing
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: divide by zero encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: overflow encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: invalid value encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: divide by zero encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: overflow encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: invalid value encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: divide by zero encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: overflow encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: invalid value encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
23:01:39 - cmdstanpy - INFO - Chain [1] start processing
23:01:40 - cmdstanpy - INFO - Chain [1] done processing
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: divide by zero encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: overflow encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: invalid value encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: divide by zero encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: overflow encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: invalid value encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: divide by zero encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: overflow encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: invalid value encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
23:01:41 - cmdstanpy - INFO - Chain [1] start processing
23:01:43 - cmdstanpy - INFO - Chain [1] done processing
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: divide by zero encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: overflow encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: invalid value encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: divide by zero encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: overflow encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: invalid value encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: divide by zero encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: overflow encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: invalid value encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
23:01:44 - cmdstanpy - INFO - Chain [1] start processing
23:01:44 - cmdstanpy - INFO - Chain [1] done processing
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: divide by zero encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: overflow encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: invalid value encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: divide by zero encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: overflow encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: invalid value encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: divide by zero encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: overflow encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: invalid value encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
23:01:45 - cmdstanpy - INFO - Chain [1] start processing
23:01:45 - cmdstanpy - INFO - Chain [1] done processing
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: divide by zero encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: overflow encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: invalid value encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: divide by zero encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: overflow encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: invalid value encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: divide by zero encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: overflow encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: invalid value encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
23:01:45 - cmdstanpy - INFO - Chain [1] start processing
23:01:45 - cmdstanpy - INFO - Chain [1] done processing

  0%|          | 0/8 [00:00<?, ?it/s]

23:01:46 - cmdstanpy - INFO - Chain [1] start processing
23:01:47 - cmdstanpy - INFO - Chain [1] done processing
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: divide by zero encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: overflow encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: invalid value encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: divide by zero encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: overflow encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: invalid value encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: divide by zero encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: overflow encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: invalid value encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
23:01:48 - cmdstanpy - INFO - Chain [1] start processing
23:01:49 - cmdstanpy - INFO - Chain [1] done processing
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: divide by zero encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: overflow encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: invalid value encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: divide by zero encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: overflow encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: invalid value encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: divide by zero encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: overflow encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: invalid value encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
23:01:50 - cmdstanpy - INFO - Chain [1] start processing
23:01:52 - cmdstanpy - INFO - Chain [1] done processing
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: divide by zero encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: overflow encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: invalid value encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: divide by zero encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: overflow encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: invalid value encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: divide by zero encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: overflow encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: invalid value encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
23:01:52 - cmdstanpy - INFO - Chain [1] start processing
23:01:54 - cmdstanpy - INFO - Chain [1] done processing
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: divide by zero encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: overflow encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: invalid value encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: divide by zero encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: overflow encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: invalid value encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: divide by zero encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: overflow encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: invalid value encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
23:01:55 - cmdstanpy - INFO - Chain [1] start processing
23:01:57 - cmdstanpy - INFO - Chain [1] done processing
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: divide by zero encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: overflow encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: invalid value encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: divide by zero encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: overflow encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: invalid value encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: divide by zero encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: overflow encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: invalid value encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
23:01:58 - cmdstanpy - INFO - Chain [1] start processing
23:01:59 - cmdstanpy - INFO - Chain [1] done processing
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: divide by zero encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: overflow encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: invalid value encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: divide by zero encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: overflow encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: invalid value encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: divide by zero encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: overflow encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: invalid value encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
23:02:00 - cmdstanpy - INFO - Chain [1] start processing
23:02:00 - cmdstanpy - INFO - Chain [1] done processing
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: divide by zero encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: overflow encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: invalid value encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: divide by zero encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: overflow encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: invalid value encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: divide by zero encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: overflow encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: invalid value encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
23:02:01 - cmdstanpy - INFO - Chain [1] start processing
23:02:01 - cmdstanpy - INFO - Chain [1] done processing
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: divide by zero encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: overflow encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: invalid value encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: divide by zero encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: overflow encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: invalid value encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: divide by zero encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: overflow encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: invalid value encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
23:02:02 - cmdstanpy - INFO - Chain [1] start processing
23:02:02 - cmdstanpy - INFO - Chain [1] done processing

  0%|          | 0/8 [00:00<?, ?it/s]

23:02:02 - cmdstanpy - INFO - Chain [1] start processing
23:02:03 - cmdstanpy - INFO - Chain [1] done processing
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: divide by zero encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: overflow encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: invalid value encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: divide by zero encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: overflow encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: invalid value encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: divide by zero encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: overflow encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: invalid value encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
23:02:04 - cmdstanpy - INFO - Chain [1] start processing
23:02:05 - cmdstanpy - INFO - Chain [1] done processing
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: divide by zero encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: overflow encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: invalid value encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: divide by zero encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: overflow encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: invalid value encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: divide by zero encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: overflow encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: invalid value encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
23:02:06 - cmdstanpy - INFO - Chain [1] start processing
23:02:08 - cmdstanpy - INFO - Chain [1] done processing
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: divide by zero encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: overflow encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: invalid value encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: divide by zero encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: overflow encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: invalid value encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: divide by zero encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: overflow encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: invalid value encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
23:02:08 - cmdstanpy - INFO - Chain [1] start processing
23:02:10 - cmdstanpy - INFO - Chain [1] done processing
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: divide by zero encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: overflow encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: invalid value encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: divide by zero encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: overflow encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: invalid value encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: divide by zero encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: overflow encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: invalid value encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
23:02:11 - cmdstanpy - INFO - Chain [1] start processing
23:02:13 - cmdstanpy - INFO - Chain [1] done processing
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: divide by zero encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: overflow encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: invalid value encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: divide by zero encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: overflow encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: invalid value encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: divide by zero encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: overflow encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: invalid value encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
23:02:13 - cmdstanpy - INFO - Chain [1] start processing
23:02:15 - cmdstanpy - INFO - Chain [1] done processing
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: divide by zero encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: overflow encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: invalid value encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: divide by zero encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: overflow encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: invalid value encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: divide by zero encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: overflow encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: invalid value encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
23:02:16 - cmdstanpy - INFO - Chain [1] start processing
23:02:16 - cmdstanpy - INFO - Chain [1] done processing
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: divide by zero encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: overflow encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: invalid value encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: divide by zero encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: overflow encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: invalid value encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: divide by zero encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: overflow encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: invalid value encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
23:02:17 - cmdstanpy - INFO - Chain [1] start processing
23:02:17 - cmdstanpy - INFO - Chain [1] done processing
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: divide by zero encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: overflow encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: invalid value encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: divide by zero encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: overflow encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: invalid value encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: divide by zero encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: overflow encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: invalid value encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
23:02:18 - cmdstanpy - INFO - Chain [1] start processing
23:02:18 - cmdstanpy - INFO - Chain [1] done processing

  0%|          | 0/8 [00:00<?, ?it/s]

23:02:18 - cmdstanpy - INFO - Chain [1] start processing
23:02:19 - cmdstanpy - INFO - Chain [1] done processing
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: divide by zero encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: overflow encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: invalid value encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: divide by zero encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: overflow encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: invalid value encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: divide by zero encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: overflow encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: invalid value encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
23:02:20 - cmdstanpy - INFO - Chain [1] start processing
23:02:21 - cmdstanpy - INFO - Chain [1] done processing
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: divide by zero encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: overflow encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: invalid value encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: divide by zero encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: overflow encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: invalid value encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: divide by zero encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: overflow encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: invalid value encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
23:02:22 - cmdstanpy - INFO - Chain [1] start processing
23:02:23 - cmdstanpy - INFO - Chain [1] done processing
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: divide by zero encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: overflow encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: invalid value encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: divide by zero encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: overflow encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: invalid value encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: divide by zero encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: overflow encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: invalid value encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
23:02:24 - cmdstanpy - INFO - Chain [1] start processing
23:02:26 - cmdstanpy - INFO - Chain [1] done processing
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: divide by zero encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: overflow encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: invalid value encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: divide by zero encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: overflow encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: invalid value encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: divide by zero encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: overflow encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: invalid value encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
23:02:27 - cmdstanpy - INFO - Chain [1] start processing
23:02:28 - cmdstanpy - INFO - Chain [1] done processing
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: divide by zero encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: overflow encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: invalid value encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: divide by zero encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: overflow encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: invalid value encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: divide by zero encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: overflow encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: invalid value encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
23:02:29 - cmdstanpy - INFO - Chain [1] start processing
23:02:31 - cmdstanpy - INFO - Chain [1] done processing
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: divide by zero encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: overflow encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: invalid value encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: divide by zero encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: overflow encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: invalid value encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: divide by zero encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: overflow encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: invalid value encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
23:02:32 - cmdstanpy - INFO - Chain [1] start processing
23:02:32 - cmdstanpy - INFO - Chain [1] done processing
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: divide by zero encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: overflow encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: invalid value encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: divide by zero encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: overflow encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: invalid value encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: divide by zero encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: overflow encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: invalid value encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
23:02:32 - cmdstanpy - INFO - Chain [1] start processing
23:02:32 - cmdstanpy - INFO - Chain [1] done processing
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: divide by zero encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: overflow encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: invalid value encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: divide by zero encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: overflow encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: invalid value encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: divide by zero encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: overflow encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: invalid value encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
23:02:33 - cmdstanpy - INFO - Chain [1] start processing
23:02:33 - cmdstanpy - INFO - Chain [1] done processing

  0%|          | 0/8 [00:00<?, ?it/s]

23:02:34 - cmdstanpy - INFO - Chain [1] start processing
23:02:35 - cmdstanpy - INFO - Chain [1] done processing
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: divide by zero encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: overflow encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: invalid value encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: divide by zero encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: overflow encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: invalid value encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: divide by zero encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: overflow encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: invalid value encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
23:02:36 - cmdstanpy - INFO - Chain [1] start processing
23:02:37 - cmdstanpy - INFO - Chain [1] done processing
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: divide by zero encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: overflow encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: invalid value encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: divide by zero encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: overflow encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: invalid value encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: divide by zero encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: overflow encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: invalid value encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
23:02:38 - cmdstanpy - INFO - Chain [1] start processing
23:02:40 - cmdstanpy - INFO - Chain [1] done processing
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: divide by zero encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: overflow encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: invalid value encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: divide by zero encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: overflow encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: invalid value encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: divide by zero encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: overflow encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: invalid value encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
23:02:41 - cmdstanpy - INFO - Chain [1] start processing
23:02:42 - cmdstanpy - INFO - Chain [1] done processing
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: divide by zero encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: overflow encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: invalid value encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: divide by zero encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: overflow encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: invalid value encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: divide by zero encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: overflow encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: invalid value encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
23:02:43 - cmdstanpy - INFO - Chain [1] start processing
23:02:45 - cmdstanpy - INFO - Chain [1] done processing
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: divide by zero encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: overflow encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: invalid value encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: divide by zero encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: overflow encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: invalid value encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: divide by zero encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: overflow encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: invalid value encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
23:02:45 - cmdstanpy - INFO - Chain [1] start processing
23:02:47 - cmdstanpy - INFO - Chain [1] done processing
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: divide by zero encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: overflow encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: invalid value encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: divide by zero encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: overflow encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: invalid value encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: divide by zero encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: overflow encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: invalid value encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
23:02:48 - cmdstanpy - INFO - Chain [1] start processing
23:02:48 - cmdstanpy - INFO - Chain [1] done processing
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: divide by zero encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: overflow encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: invalid value encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: divide by zero encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: overflow encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: invalid value encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: divide by zero encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: overflow encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: invalid value encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
23:02:48 - cmdstanpy - INFO - Chain [1] start processing
23:02:49 - cmdstanpy - INFO - Chain [1] done processing
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: divide by zero encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: overflow encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: invalid value encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: divide by zero encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: overflow encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: invalid value encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: divide by zero encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: overflow encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: invalid value encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
23:02:49 - cmdstanpy - INFO - Chain [1] start processing
23:02:49 - cmdstanpy - INFO - Chain [1] done processing

  0%|          | 0/8 [00:00<?, ?it/s]

23:02:50 - cmdstanpy - INFO - Chain [1] start processing
23:02:51 - cmdstanpy - INFO - Chain [1] done processing
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: divide by zero encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: overflow encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: invalid value encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: divide by zero encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: overflow encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: invalid value encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: divide by zero encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: overflow encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: invalid value encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
23:02:52 - cmdstanpy - INFO - Chain [1] start processing
23:02:53 - cmdstanpy - INFO - Chain [1] done processing
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: divide by zero encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: overflow encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: invalid value encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: divide by zero encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: overflow encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: invalid value encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: divide by zero encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: overflow encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: invalid value encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
23:02:54 - cmdstanpy - INFO - Chain [1] start processing
23:02:56 - cmdstanpy - INFO - Chain [1] done processing
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: divide by zero encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: overflow encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: invalid value encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: divide by zero encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: overflow encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: invalid value encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: divide by zero encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: overflow encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: invalid value encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
23:02:57 - cmdstanpy - INFO - Chain [1] start processing
23:02:58 - cmdstanpy - INFO - Chain [1] done processing
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: divide by zero encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: overflow encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: invalid value encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: divide by zero encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: overflow encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: invalid value encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: divide by zero encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: overflow encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: invalid value encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
23:02:59 - cmdstanpy - INFO - Chain [1] start processing
23:03:01 - cmdstanpy - INFO - Chain [1] done processing
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: divide by zero encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: overflow encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: invalid value encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: divide by zero encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: overflow encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: invalid value encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: divide by zero encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: overflow encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: invalid value encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
23:03:02 - cmdstanpy - INFO - Chain [1] start processing
23:03:04 - cmdstanpy - INFO - Chain [1] done processing
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: divide by zero encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: overflow encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: invalid value encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: divide by zero encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: overflow encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: invalid value encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: divide by zero encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: overflow encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: invalid value encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
23:03:04 - cmdstanpy - INFO - Chain [1] start processing
23:03:04 - cmdstanpy - INFO - Chain [1] done processing
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: divide by zero encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: overflow encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: invalid value encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: divide by zero encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: overflow encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: invalid value encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: divide by zero encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: overflow encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: invalid value encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
23:03:05 - cmdstanpy - INFO - Chain [1] start processing
23:03:05 - cmdstanpy - INFO - Chain [1] done processing
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: divide by zero encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: overflow encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: invalid value encountered in matmul
  comp = np.matmul(X, beta_c.transpose())

 Best parameters for second model: {'changepoint_prior_scale': 0.1, 'seasonality_prior_scale': 0.1, 'changepoint_range': 0.95}

/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: divide by zero encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: overflow encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: invalid value encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: divide by zero encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: overflow encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: invalid value encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)

Now we run fit the models again with their proper hyperparameters

In [ ]:
m1_tuned = Prophet(holidays=covid, **best_params_m1)
m1_tuned.fit(rental_data)

m2_tuned = Prophet(holidays=covid, **best_params_m2)
m2_tuned.add_regressor('employment_count')
m2_tuned.fit(rental_and_employment)

23:07:37 - cmdstanpy - INFO - Chain [1] start processing
23:07:37 - cmdstanpy - INFO - Chain [1] done processing
23:07:38 - cmdstanpy - INFO - Chain [1] start processing
23:07:38 - cmdstanpy - INFO - Chain [1] done processing

And then we can run the forecasts a final time

### Model 1:

In [ ]:
# Build the model excluding the year of 2025 
future = m1_tuned.make_future_dataframe(periods=12, freq='ME')
# Predict 2025 data
forecast1_tuned = m1_tuned.predict(future)

# Create a data frame with yhat as the predicted value per row and columns for uncertainty levels
forecast1_tuned[['ds', 'yhat', 'yhat_lower', 'yhat_upper']].tail(12)

/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: divide by zero encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: overflow encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: invalid value encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: divide by zero encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: overflow encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: invalid value encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: divide by zero encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: overflow encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: invalid value encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)

            ds         yhat   yhat_lower   yhat_upper
120 2025-01-31  1799.232596  1783.335798  1815.672124
121 2025-02-28  1795.882540  1779.990476  1811.628584
122 2025-03-31  1805.019445  1788.377411  1820.914082
123 2025-04-30  1819.552596  1802.264260  1835.831445
124 2025-05-31  1821.494328  1805.008539  1838.419331
125 2025-06-30  1825.081887  1808.625144  1842.485978
126 2025-07-31  1828.528297  1811.278871  1846.872454
127 2025-08-31  1827.739006  1810.091994  1847.216068
128 2025-09-30  1830.869425  1812.577483  1849.404707
129 2025-10-31  1833.757800  1814.634067  1854.116042
130 2025-11-30  1831.712779  1811.265303  1853.555060
131 2025-12-31  1832.380896  1812.997765  1853.832496

### Model 2

In [ ]:
future2 = m2_tuned.make_future_dataframe(periods=12, freq='ME')

# Prophet requires that regressor values be present in both fitting and prediction df
# Therefore the employment count will track to 2025 following real data
# First ensure dataframes are of the same type
combined_data['ds'] = pd.to_datetime(combined_data['ds'])
future2['ds'] = pd.to_datetime(future2['ds'])

# Merge data together to add 2025 employment count
future2 = future2.merge(
    combined_data[['ds', 'employment_count']],
    on='ds',
    how='left'
)
# Actual prediction
forecast2_tuned = m2_tuned.predict(future2)

# Create a data frame with yhat as the predicted value per row and columns for uncertainty levels
forecast2_tuned[['ds', 'yhat', 'yhat_lower', 'yhat_upper']].tail(12)

/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: divide by zero encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: overflow encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1421: RuntimeWarning: invalid value encountered in matmul
  comp = np.matmul(X, beta_c.transpose())
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: divide by zero encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: overflow encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1565: RuntimeWarning: invalid value encountered in matmul
  Xb_a = np.matmul(seasonal_features.values,
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: divide by zero encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: overflow encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)
/Users/jam/.pyenv/versions/MI1-2/lib/python3.10/site-packages/prophet/forecaster.py:1567: RuntimeWarning: invalid value encountered in matmul
  Xb_m = np.matmul(seasonal_features.values, beta * s_m.values)

            ds         yhat   yhat_lower   yhat_upper
120 2025-01-31  1798.811733  1783.245794  1816.192930
121 2025-02-28  1796.236728  1780.362690  1812.834246
122 2025-03-31  1805.499225  1789.177801  1822.213862
123 2025-04-30  1820.504161  1804.462104  1837.966292
124 2025-05-31  1822.886656  1805.643991  1840.234538
125 2025-06-30  1826.132220  1808.810935  1842.803621
126 2025-07-31  1829.384670  1811.806873  1847.473664
127 2025-08-31  1828.420628  1810.896351  1845.184779
128 2025-09-30  1832.585334  1813.747266  1850.989372
129 2025-10-31  1835.577104  1816.416209  1854.904178
130 2025-11-30  1833.273623  1813.352443  1852.948114
131 2025-12-31  1833.412242  1811.535652  1853.065287

### Final Comparison

In [ ]:
# Pull actual values from the year of 2025
actual_values = combined_data[combined_data['ds'] >= '2025-01-01'][['ds', 'y']].copy()

# Pull the model performances 
f1 = forecast1_tuned[forecast1_tuned['ds'] >= '2025-01-01'][['ds', 'yhat', 'yhat_lower', 'yhat_upper']].rename(
    columns={'yhat': 'yhat_m1', 'yhat_lower': 'lower_m1', 'yhat_upper': 'upper_m1'})
f2 = forecast2_tuned[forecast2_tuned['ds'] >= '2025-01-01'][['ds', 'yhat', 'yhat_lower', 'yhat_upper']].rename(
    columns={'yhat': 'yhat_m2', 'yhat_lower': 'lower_m2', 'yhat_upper': 'upper_m2'})

# Merge all the data together for easy comparison
final_comparison = actual_values.merge(f1, on='ds').merge(f2, on='ds')
# Check whether the actual value falls between the upper and lower ends of the model's prediction
final_comparison['within_m1'] = final_comparison['y'].between(final_comparison['lower_m1'], final_comparison['upper_m1'])
final_comparison['within_m2'] = final_comparison['y'].between(final_comparison['lower_m2'], final_comparison['upper_m2'])
# Confidence levels
final_comparison['width_m1'] = final_comparison['upper_m1'] - final_comparison['lower_m1']
final_comparison['width_m2'] = final_comparison['upper_m2'] - final_comparison['lower_m2']

print(final_comparison[['ds', 'y', 'yhat_m1', 'within_m1', 'yhat_m2', 'within_m2']])
print(f"\nM1 coverage: {final_comparison['within_m1'].mean():.0%}")
print(f"M2 coverage: {final_comparison['within_m2'].mean():.0%}")
print(f"M1 avg interval width: {final_comparison['width_m1'].mean():.2f}")
print(f"M2 avg interval width: {final_comparison['width_m2'].mean():.2f}")

           ds            y      yhat_m1  within_m1      yhat_m2  within_m2
0  2025-01-31  1810.942452  1799.232596       True  1798.811733       True
1  2025-02-28  1853.575750  1795.882540      False  1796.236728      False
2  2025-03-31  1873.731004  1805.019445      False  1805.499225      False
3  2025-04-30  1873.613465  1819.552596      False  1820.504161      False
4  2025-05-31  1885.487821  1821.494328      False  1822.886656      False
5  2025-06-30  1895.184392  1825.081887      False  1826.132220      False
6  2025-07-31  1907.515917  1828.528297      False  1829.384670      False
7  2025-08-31  1898.018927  1827.739006      False  1828.420628      False
8  2025-09-30  1943.949582  1830.869425      False  1832.585334      False
9  2025-10-31  1952.670747  1833.757800      False  1835.577104      False
10 2025-11-30  1947.121214  1831.712779      False  1833.273623      False
11 2025-12-31  1908.264675  1832.380896      False  1833.412242      False

M1 coverage: 8%
M2 coverage: 8%
M1 avg interval width: 35.79
M2 avg interval width: 35.61

After multiple attempts for hyper parameter tuning it seems that the default models performed the best overall.

## Statistical Analysis

Though there was a very small difference between the performance of the two models, we will continue with the statistical test just to prove that there are not different.

In [ ]:
from dieboldmariano import dm_test

# Using the midway values that were not tuned as these were the best
result = dm_test(
    midway_comparison['y'].values,
    midway_comparison['yhat_m1'].values,
    midway_comparison['yhat_m2'].values,
    h=1,          # forecast horizon = 12 months
    one_sided=False # two-sided for H0: M1 == M2
)

dm_stat, p_value = result

print("Diebold-Mariano Test")
print(f"DM Statistic: {dm_stat:.4f}")
print(f"P-value:      {p_value:.4f}")

if p_value < 0.05:
    print("Result: Reject H0. There is a tatistically significant difference between models")
    # The sign of the DM value determines which model performs better. M1 = first model M2 = second
    if dm_stat < 0:
        print("Direction: M2 (employment) outperforms M1 (base)")
    else:
        print("Direction: M1 (base) outperforms M2 (employment)")
else:
    print("Result: Fail to reject H0. There is no statistically significant difference between models")

Diebold-Mariano Test
DM Statistic: -2.6344
P-value:      0.0232
Result: Reject H0 — statistically significant difference between models
Direction: M2 (employment) outperforms M1 (base)

After checking the statistical test, it seems like M2 performed better. However, the DM test focuses on RMSE which penalizes errors. The next cell will look at the mean loss to see how the models were performing. After running the cell it can be seen that M2 has smaller errors overall which explains the results of the DM test.

(Negative values → M2 has smaller error (better)
Positive values → M1 has smaller error)

In [ ]:
# Calculation of the mean loss difference
midway_comparison['e1'] = midway_comparison['y'] - midway_comparison['yhat_m1']
midway_comparison['e2'] = midway_comparison['y'] - midway_comparison['yhat_m2']
midway_comparison['diff'] = midway_comparison['e1']**2 - midway_comparison['e2']**2

print(midway_comparison[['ds', 'diff']])
print("Mean loss diff:", midway_comparison['diff'].mean())

           ds        diff
0  2025-01-31  -38.063773
1  2025-02-28   -9.562073
2  2025-03-31  -30.533035
3  2025-04-30  -21.094555
4  2025-05-31  -53.605286
5  2025-06-30  -43.672575
6  2025-07-31  -43.607800
7  2025-08-31   -3.378783
8  2025-09-30 -230.644806
9  2025-10-31 -257.073972
10 2025-11-30 -182.310442
11 2025-12-31   41.416817
Mean loss diff: -72.67752354253969

Let's check the MAE and perform two more tests to really check what this means for the two models.

In [ ]:
from sklearn.metrics import mean_absolute_error

# Mean absolute error calculation
mae1 = mean_absolute_error(midway_comparison['y'], midway_comparison['yhat_m1'])
mae2 = mean_absolute_error(midway_comparison['y'], midway_comparison['yhat_m2'])

print(f"Model 1 MAE: {mae1}")
print(f"Model 2 MAE: {mae2}")

NameError: name 'midway_comparison' is not defined

In [ ]:
from scipy.stats import ttest_rel
from scipy.stats import wilcoxon

# Absolute error calculation
e1 = abs(midway_comparison['y'] - midway_comparison['yhat_m1'])
e2 = abs(midway_comparison['y'] - midway_comparison['yhat_m2'])

t, p = ttest_rel(e1, e2)
w, p = wilcoxon(e1, e2)

TtestResult(statistic=np.float64(-3.5307270523492664), pvalue=np.float64(0.004708817435788059), df=np.int64(11))
WilcoxonResult(statistic=np.float64(8.0), pvalue=np.float64(0.01220703125))